# Generated by Django 6.0 on 2026-01-03 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_agreements", "0001_initial"),
        ("django_catalog", "0001_initial"),
        ("django_parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("valid_from", models.DateTimeField()),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL means indefinite (no end date)",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Higher priority wins when multiple prices match",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Why this price exists (e.g., 'Preferred payer rate', 'VIP discount')",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contract/agreement for this price",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="django_agreements.agreement",
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="django_catalog.catalogitem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payer organization for this price",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        help_text="Individual person for this price",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="django_parties.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="PricedBasketItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit_price_amount",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("unit_price_currency", models.CharField(default="USD", max_length=3)),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basket_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priced",
                        to="django_catalog.basketitem",
                    ),
                ),
                (
                    "price_rule",
                    models.ForeignKey(
                        help_text="The Price record that determined this unit price",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="priced_items",
                        to="pricing.price",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priced Basket Item",
                "verbose_name_plural": "Priced Basket Items",
            },
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="price_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="price_valid_to_after_valid_from",
            ),
        ),
    ]
