# Generated by Django 6.0 on 2026-01-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_protect_scope_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="cost_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Shop cost (what shop pays). Null = unknown or same as charge.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="cost_currency",
            field=models.CharField(
                blank=True,
                help_text="Currency for shop cost. Should match currency if set.",
                max_length=3,
                null=True,
            ),
        ),
    ]
