# Generated by Django 6.0 on 2026-01-03 03:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncounterDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique identifier for this definition (e.g., 'repair_job')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                ("states", models.JSONField(help_text="List of valid state names")),
                (
                    "transitions",
                    models.JSONField(
                        help_text="Dict mapping state -> list of reachable states"
                    ),
                ),
                (
                    "initial_state",
                    models.CharField(
                        help_text="Starting state for new encounters", max_length=100
                    ),
                ),
                (
                    "terminal_states",
                    models.JSONField(
                        help_text="States that end the encounter (no outgoing transitions)"
                    ),
                ),
                (
                    "validator_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of dotted paths to validator classes",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this definition can be used for new encounters",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["key"], name="django_enco_key_956f74_idx"),
                    models.Index(
                        fields=["active"], name="django_enco_active_8906ed_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subject_id",
                    models.CharField(
                        help_text="Primary key of the subject (supports UUID and integer PKs)",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="Current state in the workflow", max_length=100
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the encounter was created"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the encounter reached a terminal state",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Domain package extensions only",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this encounter",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_type",
                    models.ForeignKey(
                        help_text="Content type of the subject",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        help_text="The definition this encounter follows",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounters",
                        to="django_encounters.encounterdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EncounterTransition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_state",
                    models.CharField(
                        help_text="State before transition", max_length=100
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        help_text="State after transition", max_length=100
                    ),
                ),
                (
                    "transitioned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the transition occurred"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Overrides, notes, validator responses",
                    ),
                ),
                (
                    "effective_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the transition happened in business terms",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the system learned about this transition",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        help_text="The encounter that was transitioned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="django_encounters.encounter",
                    ),
                ),
                (
                    "transitioned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the transition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounter_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transitioned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["definition", "state"], name="django_enco_definit_9fc070_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["subject_type", "subject_id"],
                name="django_enco_subject_9aed78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(fields=["state"], name="django_enco_state_4cc851_idx"),
        ),
        migrations.AddIndex(
            model_name="encountertransition",
            index=models.Index(
                fields=["encounter", "-transitioned_at"],
                name="django_enco_encount_5a9a28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encountertransition",
            index=models.Index(
                fields=["effective_at"], name="django_enco_effecti_5d81f3_idx"
            ),
        ),
    ]
