# Generated by Django 6.0 on 2026-01-02 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_encounters", "0002_add_transition_time_semantics"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="encountertransition",
            new_name="django_enco_effecti_5d81f3_idx",
            old_name="django_enco_effecti_4g5h6i_idx",
        ),
        migrations.AlterField(
            model_name="encounter",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="encounterdefinition",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="encountertransition",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
