# Generated by Django 6.0 on 2026-01-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_encounters",
            "0003_rename_django_enco_effecti_4g5h6i_idx_django_enco_effecti_5d81f3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="subject_id",
            field=models.CharField(
                help_text="Primary key of the subject (supports UUID and integer PKs)",
                max_length=255,
            ),
        ),
    ]
