# Generated by Django 6.0 on 2026-01-02 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "party_a_id",
                    models.CharField(
                        help_text="ID of party A (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "party_b_id",
                    models.CharField(
                        help_text="ID of party B (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        help_text="Agreement type (order, subscription, consent, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "scope_ref_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID of the scope reference",
                        max_length=255,
                    ),
                ),
                (
                    "terms",
                    models.JSONField(
                        help_text="Current agreement terms (projection of latest version)"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        help_text="When the agreement becomes effective"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the agreement expires (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "agreed_at",
                    models.DateTimeField(help_text="When the agreement was made"),
                ),
                (
                    "current_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Current version (synced with max AgreementVersion.version)",
                    ),
                ),
                (
                    "agreed_by",
                    models.ForeignKey(
                        help_text="User who made the agreement",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party_a_content_type",
                    models.ForeignKey(
                        help_text="Content type of party A",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "party_b_content_type",
                    models.ForeignKey(
                        help_text="Content type of party B",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "scope_ref_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of the scope reference",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgreementVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(help_text="Version number")),
                (
                    "terms",
                    models.JSONField(
                        help_text="Terms snapshot for this version (immutable)"
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for this version/amendment"),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        help_text="The agreement this version belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="django_agreements.agreement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this version",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["party_a_content_type", "party_a_id"],
                name="django_agre_party_a_bc328c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["party_b_content_type", "party_b_id"],
                name="django_agre_party_b_d48610_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["scope_type"], name="django_agre_scope_t_a4650d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="django_agre_valid_f_e77c19_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="agreements_valid_to_after_valid_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementversion",
            constraint=models.UniqueConstraint(
                fields=("agreement", "version"), name="unique_agreement_version"
            ),
        ),
    ]
