# Generated by Django 6.0 on 2026-01-03 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scope",
                    models.CharField(
                        help_text="Sequence scope, e.g., 'invoice', 'order', 'ticket'",
                        max_length=50,
                    ),
                ),
                (
                    "org_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the organization (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="Prefix for formatted value, e.g., 'INV-', 'ORD-'",
                        max_length=20,
                    ),
                ),
                (
                    "current_value",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Current sequence value"
                    ),
                ),
                (
                    "pad_width",
                    models.PositiveSmallIntegerField(
                        default=6, help_text="Zero-padding width for the number portion"
                    ),
                ),
                (
                    "include_year",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include the year in the formatted value",
                    ),
                ),
                (
                    "org_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of the organization model",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "org_content_type", "org_id"],
                        name="django_sequ_scope_5e9887_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "org_content_type", "org_id"),
                        name="sequence_unique_per_scope_org",
                    )
                ],
            },
        ),
    ]
