# Generated by Django 6.0 on 2026-01-08 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "media_url_resolver_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "entitlement_checker_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "default_seo_title_suffix",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "default_og_image_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("nav_json", models.JSONField(blank=True, default=list)),
                ("footer_json", models.JSONField(blank=True, default=dict)),
                ("api_cache_ttl_seconds", models.PositiveIntegerField(default=60)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "CMS Settings",
                "verbose_name_plural": "CMS Settings",
            },
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=200)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("authenticated", "Authenticated Users"),
                            ("role", "Role-based"),
                            ("entitlement", "Entitlement-based"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("required_roles", models.JSONField(blank=True, default=list)),
                ("required_entitlements", models.JSONField(blank=True, default=list)),
                ("seo_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "og_image_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "canonical_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("robots", models.CharField(default="index, follow", max_length=50)),
                ("published_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_indexable", models.BooleanField(default=True)),
                ("template_key", models.CharField(default="default", max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("block_type", models.CharField(db_index=True, max_length=50)),
                ("data", models.JSONField(default=dict)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="django_cms_core.contentpage",
                    ),
                ),
            ],
            options={
                "ordering": ["page", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("from_path", models.CharField(max_length=500)),
                ("to_path", models.CharField(max_length=500)),
                ("is_permanent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["from_path"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("from_path",),
                        name="unique_redirect_from_path",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contentpage",
            index=models.Index(
                fields=["slug", "status"], name="django_cms__slug_5d215c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentpage",
            index=models.Index(
                fields=["status", "published_at"], name="django_cms__status_022fea_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentpage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("slug",),
                name="unique_page_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="contentblock",
            index=models.Index(
                fields=["page", "sequence"], name="django_cms__page_id_9776a7_idx"
            ),
        ),
    ]
