# Generated by Django 6.0 on 2026-01-11 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_cms_core", "0001_initial"),
        ("django_parties", "0004_add_lead_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_posts",
                to="django_parties.person",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="excerpt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="featured_image_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="page_type",
            field=models.CharField(
                choices=[("page", "Page"), ("post", "Blog Post")],
                db_index=True,
                default="page",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="reading_time_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("slug",),
                        name="unique_blog_category_slug",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="contentpage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="django_cms_core.blogcategory",
            ),
        ),
    ]
