# Generated by Django 6.0 on 2026-01-03 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the decision was effective in the business world",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the system recorded the decision",
                    ),
                ),
                (
                    "authority_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Role/org snapshot at decision time",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        help_text="ID of target object (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action taken: 'commit', 'approve', 'reverse', etc.",
                        max_length=50,
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Immutable evidence of inputs at decision time"
                    ),
                ),
                (
                    "outcome",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Result reference (e.g., created work item IDs)",
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the decision became permanent",
                        null=True,
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the decision",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions_as_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "on_behalf_of_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User on whose behalf the decision was made (delegation)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions_on_behalf",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        help_text="ContentType of the target object",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="django_deci_target__0329d4_idx",
                    ),
                    models.Index(
                        fields=["actor_user"], name="django_deci_actor_u_e105b4_idx"
                    ),
                    models.Index(
                        fields=["action"], name="django_deci_action_2bb1db_idx"
                    ),
                    models.Index(
                        fields=["effective_at"], name="django_deci_effecti_287c85_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        help_text="Operation scope, e.g., 'basket_commit', 'payment'",
                        max_length=100,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Client-provided or derived idempotency key",
                        max_length=255,
                    ),
                ),
                (
                    "request_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of request body for mismatch detection",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this key can be cleaned up",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When processing started (for stale lock detection)",
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                (
                    "response_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Cached response for successful operations",
                        null=True,
                    ),
                ),
                (
                    "result_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of created object (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "result_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="ContentType of the created object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "key"], name="django_deci_scope_186c49_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="django_deci_expires_1e91e3_idx"
                    ),
                    models.Index(fields=["state"], name="django_deci_state_417e9e_idx"),
                ],
                "unique_together": {("scope", "key")},
            },
        ),
    ]
