# Generated by Django 6.0 on 2026-01-10 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable email sending"
                    ),
                ),
                (
                    "email_provider",
                    models.CharField(
                        choices=[
                            ("console", "Console (Development)"),
                            ("ses_api", "Amazon SES (Production)"),
                        ],
                        default="console",
                        help_text="Email delivery provider",
                        max_length=20,
                    ),
                ),
                (
                    "email_from_address",
                    models.EmailField(
                        blank=True,
                        help_text="Default sender email address",
                        max_length=254,
                    ),
                ),
                (
                    "email_from_name",
                    models.CharField(
                        blank=True,
                        help_text="Default sender display name",
                        max_length=100,
                    ),
                ),
                (
                    "email_reply_to",
                    models.EmailField(
                        blank=True,
                        help_text="Reply-to address (optional)",
                        max_length=254,
                    ),
                ),
                (
                    "ses_region",
                    models.CharField(
                        blank=True,
                        default="us-east-1",
                        help_text="AWS region for SES",
                        max_length=20,
                    ),
                ),
                (
                    "ses_access_key_id",
                    models.CharField(
                        blank=True, help_text="AWS access key ID", max_length=100
                    ),
                ),
                (
                    "ses_secret_access_key",
                    models.CharField(
                        blank=True, help_text="AWS secret access key", max_length=100
                    ),
                ),
                (
                    "ses_configuration_set",
                    models.CharField(
                        blank=True,
                        help_text="SES configuration set for tracking (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, help_text="Enable SMS sending"),
                ),
                (
                    "sms_provider",
                    models.CharField(
                        choices=[("console", "Console (Development)")],
                        default="console",
                        help_text="SMS delivery provider",
                        max_length=20,
                    ),
                ),
                (
                    "sms_from_number",
                    models.CharField(
                        blank=True,
                        help_text="Default sender phone number (E.164 format)",
                        max_length=20,
                    ),
                ),
                (
                    "default_channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        default="email",
                        help_text="Default channel when not specified",
                        max_length=10,
                    ),
                ),
                (
                    "sandbox_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Log messages but don't actually send (for testing)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication Settings",
                "verbose_name_plural": "Communication Settings",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'booking_confirmation', 'day_of_reminder')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("reminder", "Reminder"),
                            ("alert", "Alert"),
                            ("announcement", "Announcement"),
                        ],
                        default="transactional",
                        help_text="Determines default channel routing",
                        max_length=20,
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject line (Django template syntax)",
                        max_length=500,
                    ),
                ),
                (
                    "email_body_text",
                    models.TextField(
                        blank=True,
                        help_text="Plain text email body (Django template syntax)",
                    ),
                ),
                (
                    "email_body_html",
                    models.TextField(
                        blank=True,
                        help_text="HTML email body (optional, Django template syntax)",
                    ),
                ),
                (
                    "sms_body",
                    models.CharField(
                        blank=True,
                        help_text="SMS message content (Django template syntax)",
                        max_length=1600,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active templates can be used for sending",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_message_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Template",
                "verbose_name_plural": "Message Templates",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Sent"), ("inbound", "Received")],
                        default="outbound",
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=10
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transactional", "Transactional"),
                            ("reminder", "Reminder"),
                            ("alert", "Alert"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "from_address",
                    models.CharField(
                        help_text="Sender address (email or phone)", max_length=255
                    ),
                ),
                (
                    "to_address",
                    models.CharField(
                        help_text="Recipient address (email or phone)", max_length=255
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line (email only)",
                        max_length=500,
                    ),
                ),
                ("body_text", models.TextField(help_text="Plain text content")),
                (
                    "body_html",
                    models.TextField(blank=True, help_text="HTML content (email only)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider that sent this message (e.g., 'ses', 'twilio')",
                        max_length=50,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="External message ID from provider",
                        max_length=255,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if status is 'failed'"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the message was sent", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="When delivery was confirmed", null=True
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of related object (e.g., booking, excursion)",
                        max_length=255,
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of related object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template used to generate this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="django_communication.messagetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "status"],
                        name="django_comm_channel_88a391_idx",
                    ),
                    models.Index(
                        fields=["to_address"], name="django_comm_to_addr_9cdaf6_idx"
                    ),
                    models.Index(
                        fields=["direction", "created_at"],
                        name="django_comm_directi_b91a3b_idx",
                    ),
                    models.Index(
                        fields=["related_content_type", "related_object_id"],
                        name="django_comm_related_cc4346_idx",
                    ),
                ],
            },
        ),
    ]
