# Generated by Django 6.0 on 2026-01-10 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_communication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., transactional, marketing)",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this profile", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of when this profile is used"
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        help_text="Sender display name (e.g., 'Happy Diving')",
                        max_length=100,
                    ),
                ),
                (
                    "from_address_en",
                    models.EmailField(
                        help_text="Sender email for English messages", max_length=254
                    ),
                ),
                (
                    "reply_to_en",
                    models.EmailField(
                        blank=True,
                        help_text="Reply-to address for English messages (optional)",
                        max_length=254,
                    ),
                ),
                (
                    "ses_configuration_set_en",
                    models.CharField(
                        blank=True,
                        help_text="SES configuration set for English (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "from_address_es",
                    models.EmailField(
                        help_text="Sender email for Spanish messages", max_length=254
                    ),
                ),
                (
                    "reply_to_es",
                    models.EmailField(
                        blank=True,
                        help_text="Reply-to address for Spanish messages (optional)",
                        max_length=254,
                    ),
                ),
                (
                    "ses_configuration_set_es",
                    models.CharField(
                        blank=True,
                        help_text="SES configuration set for Spanish (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this profile can be used for sending",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Profile",
                "verbose_name_plural": "Message Profiles",
                "ordering": ["slug"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="recipient_locale",
            field=models.CharField(
                blank=True,
                help_text="Recipient's locale used for identity selection (e.g., 'en', 'es')",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.CharField(
                blank=True, help_text="Reply-to address (email only)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="communicationsettings",
            name="email_from_address",
            field=models.EmailField(
                blank=True,
                help_text="Fallback sender email (used if no profile set)",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="communicationsettings",
            name="email_from_name",
            field=models.CharField(
                blank=True, help_text="Fallback sender display name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="communicationsettings",
            name="email_reply_to",
            field=models.EmailField(
                blank=True, help_text="Fallback reply-to address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="communicationsettings",
            name="ses_configuration_set",
            field=models.CharField(
                blank=True,
                help_text="SES configuration set for tracking (fallback, prefer profile)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="default_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Default message profile for email identity (from address, reply-to)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="django_communication.messageprofile",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Message profile used for sender identity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="django_communication.messageprofile",
            ),
        ),
    ]
