# Generated by Django 6.0 on 2026-01-11 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "django_communication",
            "0002_messageprofile_message_recipient_locale_and_more",
        ),
        ("django_parties", "0004_add_lead_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("staff", "Staff"),
                            ("system", "System"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When participant last read the conversation",
                        null=True,
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to notify this participant of new messages",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Participant",
                "verbose_name_plural": "Conversation Participants",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="external_message_id",
            field=models.CharField(
                blank=True, help_text="Email Message-ID header value", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="in_reply_to_id",
            field=models.CharField(
                blank=True, help_text="Email In-Reply-To header value", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Person who sent this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to="django_parties.person",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("in_app", "In-App Message"),
                    ("whatsapp", "WhatsApp"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject/title of conversation (often from email subject)",
                        max_length=500,
                    ),
                ),
                (
                    "normalized_subject",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Subject with Re:/Fwd: stripped for thread matching",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True, help_text="ID of related object", max_length=255
                    ),
                ),
                (
                    "email_thread_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Email In-Reply-To/References header for threading",
                        max_length=255,
                    ),
                ),
                (
                    "primary_channel",
                    models.CharField(
                        blank=True,
                        help_text="Primary channel for this conversation (email, sms, in_app)",
                        max_length=20,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp of most recent message (denormalized for sorting)",
                        null=True,
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the conversation was closed",
                        null=True,
                    ),
                ),
                (
                    "assigned_to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member responsible for this conversation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who closed this conversation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who created this conversation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of related object (e.g., Booking)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="Conversation this message belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="django_communication.conversation",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="django_comm_convers_d119bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender_person"], name="django_comm_sender__19d10e_idx"
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="django_communication.conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="person",
            field=models.ForeignKey(
                help_text="Person participating in conversation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_participations",
                to="django_parties.person",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["status", "-last_message_at"],
                name="django_comm_status_6a0d62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["assigned_to_user", "status", "-last_message_at"],
                name="django_comm_assigne_b77f3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["related_content_type", "related_object_id"],
                name="django_comm_related_b8e0fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["conversation", "person"], name="django_comm_convers_30fa5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["person", "-last_read_at"],
                name="django_comm_person__cc1de1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["conversation", "role"], name="django_comm_convers_5b437a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationparticipant",
            constraint=models.UniqueConstraint(
                fields=("conversation", "person"), name="unique_conversation_person"
            ),
        ),
    ]
