# Generated by Django 6.0 on 2026-01-11 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_communication", "0003_conversation_models"),
        ("django_parties", "0004_add_lead_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationsettings",
            name="notification_fallback_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable fallback from push to email/SMS when push fails",
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="push_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable Web Push notifications"
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="push_failure_threshold",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Deactivate subscription after this many consecutive failures",
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="vapid_contact_email",
            field=models.EmailField(
                blank=True, help_text="Contact email for VAPID claims", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="vapid_private_key",
            field=models.CharField(
                blank=True,
                help_text="VAPID private key for Web Push (keep secret!)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="vapid_public_key",
            field=models.CharField(
                blank=True, help_text="VAPID public key for Web Push", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("in_app", "In-App Message"),
                    ("whatsapp", "WhatsApp"),
                    ("push", "Web Push"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.URLField(
                        help_text="Push service endpoint URL", max_length=500
                    ),
                ),
                (
                    "p256dh_key",
                    models.CharField(
                        help_text="Public key for encryption (p256dh)", max_length=200
                    ),
                ),
                (
                    "auth_key",
                    models.CharField(
                        help_text="Auth secret for encryption", max_length=50
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser user agent string",
                        max_length=500,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly device name (e.g., 'Chrome on Windows')",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this subscription is active"
                    ),
                ),
                (
                    "last_successful_push",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last push was successfully delivered",
                        null=True,
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Consecutive push failures (reset on success)",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person who owns this subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="django_parties.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "is_active"],
                        name="django_comm_person__895cc6_idx",
                    ),
                    models.Index(
                        fields=["endpoint"], name="django_comm_endpoin_e96c2d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "endpoint"), name="unique_person_endpoint"
                    )
                ],
            },
        ),
    ]
