# Generated by Django 6.0 on 2026-01-11 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_communication", "0004_push_subscriptions"),
        ("django_parties", "0004_add_lead_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="CannedResponseTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (e.g., 'Booking', 'FAQ')",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Canned Response Tag",
                "verbose_name_plural": "Canned Response Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="canned_rendered_body",
            field=models.TextField(
                blank=True,
                help_text="Snapshot of rendered canned response at send time",
            ),
        ),
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Short label shown in picker UI", max_length=200
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Message content with {{ variable }} placeholders"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("any", "Any Channel"),
                            ("chat", "Chat/In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        default="any",
                        help_text="Which channel(s) this response is for",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Language code (e.g., 'en', 'es'). Blank = all languages",
                        max_length=10,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private (Creator Only)"),
                            ("org", "Organization"),
                            ("public", "Public (All Users)"),
                        ],
                        default="org",
                        help_text="Who can use this response",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active responses can be used"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who created this response",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_canned_responses",
                        to="django_parties.person",
                    ),
                ),
                (
                    "owner_party",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that owns this response (for org visibility)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for filtering and organization",
                        related_name="canned_responses",
                        to="django_communication.cannedresponsetag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canned Response",
                "verbose_name_plural": "Canned Responses",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="canned_response",
            field=models.ForeignKey(
                blank=True,
                help_text="Canned response used to create this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="django_communication.cannedresponse",
            ),
        ),
        migrations.AddIndex(
            model_name="cannedresponse",
            index=models.Index(
                fields=["visibility", "is_active"],
                name="django_comm_visibil_7ecc1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cannedresponse",
            index=models.Index(
                fields=["owner_party", "is_active"],
                name="django_comm_owner_p_b8c099_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cannedresponse",
            index=models.Index(
                fields=["channel", "is_active"], name="django_comm_channel_5a22cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cannedresponse",
            index=models.Index(
                fields=["created_by", "is_active"],
                name="django_comm_created_cd314a_idx",
            ),
        ),
    ]
