# Generated by Django 6.0 on 2026-01-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_communication",
            "0005_cannedresponsetag_message_canned_rendered_body_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="event_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Event type that triggers this template (e.g., 'booking.confirmed', 'class.signup.started')",
                max_length=100,
            ),
        ),
    ]
