# Generated by Django 6.0 on 2026-01-11 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_communication", "0006_messagetemplate_event_type"),
        ("django_parties", "0004_add_lead_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="conversation_type",
            field=models.CharField(
                choices=[("direct", "Direct (1:1)"), ("group", "Group")],
                db_index=True,
                default="direct",
                help_text="Type of conversation: direct (1:1) or group",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="created_by_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Person who created this conversation (for groups)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_conversations",
                to="django_parties.person",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title for group conversations (optional for direct)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Person who invited this participant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations_sent",
                to="django_parties.person",
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="joined_at",
            field=models.DateTimeField(
                blank=True, help_text="When participant joined/accepted", null=True
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="left_at",
            field=models.DateTimeField(
                blank=True, help_text="When participant left or was removed", null=True
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("invited", "Invited"),
                    ("left", "Left"),
                    ("removed", "Removed"),
                ],
                db_index=True,
                default="active",
                help_text="Participant membership state",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conversationparticipant",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("system", "System"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["conversation_type", "status"],
                name="django_comm_convers_685226_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["conversation", "state"], name="django_comm_convers_aca289_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["person", "state"], name="django_comm_person__2a1cb4_idx"
            ),
        ),
    ]
