# Generated by Django 6.0 on 2026-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_communication", "0007_group_conversations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="direction",
            field=models.CharField(
                choices=[
                    ("outbound", "Sent"),
                    ("inbound", "Received"),
                    ("system", "System"),
                ],
                default="outbound",
                max_length=10,
            ),
        ),
    ]
