# Generated by Django 5.1.5 on 2025-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_communication', '0010_backfill_conversation_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When message was read/viewed by recipient', null=True),
        ),
    ]
