# Generated by Django 6.0 on 2026-01-03 22:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_agreements", "0001_initial"),
        ("django_catalog", "0001_initial"),
        ("django_encounters", "0001_initial"),
        ("django_geo", "0003_place_place_valid_latitude_and_more"),
        ("django_parties", "0001_initial"),
        ("invoicing", "0002_add_line_item_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiverProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certification_level",
                    models.CharField(
                        choices=[
                            ("sd", "Scuba Diver"),
                            ("ow", "Open Water"),
                            ("aow", "Advanced Open Water"),
                            ("rescue", "Rescue Diver"),
                            ("dm", "Divemaster"),
                            ("instructor", "Instructor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "certification_agency",
                    models.CharField(
                        help_text="e.g., PADI, SSI, NAUI, SDI", max_length=50
                    ),
                ),
                ("certification_number", models.CharField(max_length=100)),
                ("certification_date", models.DateField()),
                ("total_dives", models.PositiveIntegerField(default=0)),
                ("medical_clearance_date", models.DateField(blank=True, null=True)),
                (
                    "medical_clearance_valid_until",
                    models.DateField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diver_profile",
                        to="django_parties.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiveSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("max_depth_meters", models.PositiveIntegerField()),
                (
                    "min_certification_level",
                    models.CharField(
                        choices=[
                            ("sd", "Scuba Diver"),
                            ("ow", "Open Water"),
                            ("aow", "Advanced Open Water"),
                            ("rescue", "Rescue Diver"),
                            ("dm", "Divemaster"),
                            ("instructor", "Instructor"),
                        ],
                        default="ow",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_sites",
                        to="django_geo.place",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiveTrip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("departure_time", models.DateTimeField()),
                ("return_time", models.DateTimeField()),
                ("max_divers", models.PositiveIntegerField()),
                (
                    "price_per_diver",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("boarding", "Boarding"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dive_trips_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dive_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dive_trips",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "dive_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="diveops.divesite",
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_trip",
                        to="django_encounters.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ["-departure_time"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "basket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_bookings",
                        to="django_catalog.basket",
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dive_bookings_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_bookings",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "waiver_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_bookings",
                        to="django_agreements.agreement",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="diveops.divetrip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripRoster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("dive_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_entry",
                        to="diveops.booking",
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkins_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_roster_entries",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster",
                        to="diveops.divetrip",
                    ),
                ),
            ],
            options={
                "ordering": ["checked_in_at"],
            },
        ),
        migrations.AddIndex(
            model_name="diverprofile",
            index=models.Index(
                fields=["certification_level"], name="diveops_div_certifi_2f209f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diverprofile",
            index=models.Index(
                fields=["person"], name="diveops_div_person__98a7f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diverprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_dives__gte", 0)),
                name="diverprofile_total_dives_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="divesite",
            index=models.Index(
                fields=["is_active"], name="diveops_div_is_acti_398e64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="divesite",
            index=models.Index(
                fields=["min_certification_level"],
                name="diveops_div_min_cer_93bfae_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_depth_meters__gt", 0)),
                name="divesite_max_depth_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="divesite_valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="divesite_valid_longitude",
            ),
        ),
        migrations.AddIndex(
            model_name="divetrip",
            index=models.Index(
                fields=["departure_time"], name="diveops_div_departu_4027e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="divetrip",
            index=models.Index(fields=["status"], name="diveops_div_status_f7338e_idx"),
        ),
        migrations.AddIndex(
            model_name="divetrip",
            index=models.Index(
                fields=["dive_shop", "status"], name="diveops_div_dive_sh_634890_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="divetrip",
            constraint=models.CheckConstraint(
                condition=models.Q(("return_time__gt", models.F("departure_time"))),
                name="divetrip_return_after_departure",
            ),
        ),
        migrations.AddConstraint(
            model_name="divetrip",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_divers__gt", 0)),
                name="divetrip_max_divers_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="divetrip",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_per_diver__gte", 0)),
                name="divetrip_price_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["trip", "status"], name="diveops_boo_trip_id_f2d188_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["diver"], name="diveops_boo_diver_i_c173f1_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("trip", "diver"), name="unique_booking_per_diver_trip"
            ),
        ),
        migrations.AddIndex(
            model_name="triproster",
            index=models.Index(fields=["trip"], name="diveops_tri_trip_id_5c64bd_idx"),
        ),
        migrations.AddConstraint(
            model_name="triproster",
            constraint=models.UniqueConstraint(
                fields=("trip", "diver"), name="unique_roster_entry_per_diver_trip"
            ),
        ),
    ]
