# Generated by Django 6.0 on 2026-01-04 16:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_agreements", "0001_initial"),
        ("django_catalog", "0001_initial"),
        ("django_documents", "0001_initial"),
        ("django_encounters", "0001_initial"),
        ("django_geo", "0003_place_place_valid_latitude_and_more"),
        ("django_parties", "0001_initial"),
        ("invoicing", "0002_add_line_item_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationLevel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.SlugField(
                        help_text="Short code like 'ow', 'aow', 'dm' (unique per agency)",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name like 'Open Water Diver'", max_length=100
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Numeric rank for comparison (higher = more advanced)"
                    ),
                ),
                (
                    "max_depth_m",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maximum depth in meters for this level (optional)",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "agency",
                    models.ForeignKey(
                        help_text="Certification agency that defines this level (PADI, SSI, etc.)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certification_levels",
                        to="django_parties.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["agency", "rank"],
            },
        ),
        migrations.CreateModel(
            name="DiverProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "certification_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sd", "Scuba Diver"),
                            ("ow", "Open Water"),
                            ("aow", "Advanced Open Water"),
                            ("rescue", "Rescue Diver"),
                            ("dm", "Divemaster"),
                            ("instructor", "Instructor"),
                        ],
                        default="",
                        help_text="DEPRECATED: Use DiverCertification model instead",
                        max_length=20,
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DEPRECATED: Use DiverCertification model instead",
                        max_length=100,
                    ),
                ),
                (
                    "certification_date",
                    models.DateField(
                        blank=True,
                        help_text="DEPRECATED: Use DiverCertification model instead",
                        null=True,
                    ),
                ),
                ("total_dives", models.PositiveIntegerField(default=0)),
                ("medical_clearance_date", models.DateField(blank=True, null=True)),
                (
                    "medical_clearance_valid_until",
                    models.DateField(blank=True, null=True),
                ),
                ("waiver_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "certification_agency",
                    models.ForeignKey(
                        blank=True,
                        help_text="DEPRECATED: Use DiverCertification model instead",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diver_profiles",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diver_profile",
                        to="django_parties.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiverCertification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        help_text="Certification card number",
                        max_length=100,
                    ),
                ),
                (
                    "issued_on",
                    models.DateField(
                        blank=True, help_text="Date certification was issued", null=True
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if certification never expires",
                        null=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level",
                    models.ForeignKey(
                        help_text="Certification level (determines agency)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diver_certifications",
                        to="diveops.certificationlevel",
                    ),
                ),
                (
                    "proof_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary proof document (certification card photo/scan)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certification_proofs",
                        to="django_documents.document",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="diveops.diverprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-level__rank", "-issued_on"],
            },
        ),
        migrations.CreateModel(
            name="DiveSite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("max_depth_meters", models.PositiveIntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Site rating 1-5 (null = unrated)",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization (e.g., ['reef', 'coral', 'wreck'])",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_certification_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Minimum certification required (null = no requirement)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dive_sites",
                        to="diveops.certificationlevel",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        help_text="Location (owned per site, not shared)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dive_sites",
                        to="django_geo.place",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Excursion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("departure_time", models.DateTimeField()),
                ("return_time", models.DateTimeField()),
                ("max_divers", models.PositiveIntegerField()),
                (
                    "price_per_diver",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("boarding", "Boarding"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excursions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dive_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excursions",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "dive_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excursions",
                        to="diveops.divesite",
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excursion",
                        to="django_encounters.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ["-departure_time"],
            },
        ),
        migrations.CreateModel(
            name="Dive",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        help_text="Dive number within the excursion (1, 2, 3...)"
                    ),
                ),
                ("planned_start", models.DateTimeField()),
                (
                    "planned_duration_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Planned dive duration in minutes",
                        null=True,
                    ),
                ),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "max_depth_meters",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maximum depth reached in meters",
                        null=True,
                    ),
                ),
                (
                    "bottom_time_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Total bottom time in minutes", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "dive_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dives",
                        to="diveops.divesite",
                    ),
                ),
                (
                    "excursion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dives",
                        to="diveops.excursion",
                    ),
                ),
            ],
            options={
                "ordering": ["excursion", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "basket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_bookings",
                        to="django_catalog.basket",
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dive_bookings_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_bookings",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "waiver_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_bookings",
                        to="django_agreements.agreement",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "excursion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="diveops.excursion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExcursionRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("certification", "Certification Level"),
                            ("medical", "Medical Clearance"),
                            ("gear", "Equipment/Gear"),
                            ("experience", "Dive Experience"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_dives",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum number of logged dives",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "certification_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_requirements",
                        to="diveops.certificationlevel",
                    ),
                ),
                (
                    "excursion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="diveops.excursion",
                    ),
                ),
            ],
            options={
                "ordering": ["requirement_type"],
            },
        ),
        migrations.CreateModel(
            name="ExcursionRoster",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DIVER", "Diver"),
                            ("DM", "Divemaster"),
                            ("INSTRUCTOR", "Instructor"),
                        ],
                        default="DIVER",
                        help_text="Role on this excursion (diver, divemaster, or instructor)",
                        max_length=20,
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("dive_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_entry",
                        to="diveops.booking",
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkins_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excursion_roster_entries",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "excursion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster",
                        to="diveops.excursion",
                    ),
                ),
            ],
            options={
                "ordering": ["checked_in_at"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catalog item representing this trip package",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_packages",
                        to="django_catalog.catalogitem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_packages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dive_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_packages",
                        to="django_parties.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="excursion",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Trip package this excursion belongs to (null = standalone)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excursions",
                to="diveops.trip",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificationlevel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("agency", "code"),
                name="diveops_unique_agency_level_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificationlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("rank__gt", 0)),
                name="diveops_cert_level_rank_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificationlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_depth_m__isnull", True),
                    ("max_depth_m__gt", 0),
                    _connector="OR",
                ),
                name="diveops_cert_level_depth_gt_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="diverprofile",
            index=models.Index(
                fields=["certification_level"], name="diveops_div_certifi_2f209f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diverprofile",
            index=models.Index(
                fields=["person"], name="diveops_div_person__98a7f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diverprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_dives__gte", 0)),
                name="diveops_diver_total_dives_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="divercertification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("diver", "level"),
                name="diveops_unique_active_certification",
            ),
        ),
        migrations.AddConstraint(
            model_name="divercertification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_on__isnull", True),
                    ("issued_on__isnull", True),
                    ("expires_on__gt", models.F("issued_on")),
                    _connector="OR",
                ),
                name="diveops_cert_expires_after_issued",
            ),
        ),
        migrations.AddIndex(
            model_name="divesite",
            index=models.Index(
                fields=["is_active"], name="diveops_div_is_acti_398e64_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_depth_meters__gt", 0)),
                name="diveops_site_depth_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True),
                    models.Q(("rating__gte", 1), ("rating__lte", 5)),
                    _connector="OR",
                ),
                name="diveops_site_rating_1_to_5",
            ),
        ),
        migrations.AddIndex(
            model_name="dive",
            index=models.Index(
                fields=["excursion", "sequence"], name="diveops_div_excursi_0cc369_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dive",
            constraint=models.UniqueConstraint(
                fields=("excursion", "sequence"), name="diveops_dive_unique_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="dive",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="diveops_dive_sequence_gt_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["excursion", "status"], name="diveops_boo_excursi_d9a90c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["diver"], name="diveops_boo_diver_i_c173f1_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "confirmed", "checked_in"])
                ),
                fields=("excursion", "diver"),
                name="diveops_booking_one_active_per_excursion",
            ),
        ),
        migrations.AddConstraint(
            model_name="excursionrequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("excursion", "requirement_type"),
                name="diveops_unique_requirement_type_per_excursion",
            ),
        ),
        migrations.AddIndex(
            model_name="excursionroster",
            index=models.Index(
                fields=["excursion"], name="diveops_exc_excursi_897366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excursionroster",
            index=models.Index(fields=["role"], name="diveops_exc_role_dceace_idx"),
        ),
        migrations.AddConstraint(
            model_name="excursionroster",
            constraint=models.UniqueConstraint(
                fields=("excursion", "diver"), name="diveops_roster_one_per_excursion"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["start_date"], name="diveops_tri_start_d_26f3dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["status"], name="diveops_tri_status_94abe0_idx"),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["dive_shop", "status"], name="diveops_tri_dive_sh_45a961_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="diveops_trip_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="excursion",
            index=models.Index(
                fields=["departure_time"], name="diveops_exc_departu_5e55e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excursion",
            index=models.Index(fields=["status"], name="diveops_exc_status_c21677_idx"),
        ),
        migrations.AddIndex(
            model_name="excursion",
            index=models.Index(
                fields=["dive_shop", "status"], name="diveops_exc_dive_sh_ca03a9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="excursion",
            constraint=models.CheckConstraint(
                condition=models.Q(("return_time__gt", models.F("departure_time"))),
                name="diveops_excursion_return_after_departure",
            ),
        ),
        migrations.AddConstraint(
            model_name="excursion",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_divers__gt", 0)),
                name="diveops_excursion_max_divers_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="excursion",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_per_diver__gte", 0)),
                name="diveops_excursion_price_gte_zero",
            ),
        ),
    ]
