# Generated by Django 6.0 on 2026-01-03 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0001_initial"),
        ("django_agreements", "0001_initial"),
        ("django_catalog", "0001_initial"),
        ("django_encounters", "0001_initial"),
        ("django_geo", "0003_place_place_valid_latitude_and_more"),
        ("django_parties", "0001_initial"),
        ("invoicing", "0002_add_line_item_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking_per_diver_trip",
        ),
        migrations.RemoveConstraint(
            model_name="diverprofile",
            name="diverprofile_total_dives_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="divesite",
            name="divesite_max_depth_positive",
        ),
        migrations.RemoveConstraint(
            model_name="divesite",
            name="divesite_valid_latitude",
        ),
        migrations.RemoveConstraint(
            model_name="divesite",
            name="divesite_valid_longitude",
        ),
        migrations.RemoveConstraint(
            model_name="divetrip",
            name="divetrip_return_after_departure",
        ),
        migrations.RemoveConstraint(
            model_name="divetrip",
            name="divetrip_max_divers_positive",
        ),
        migrations.RemoveConstraint(
            model_name="divetrip",
            name="divetrip_price_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="triproster",
            name="unique_roster_entry_per_diver_trip",
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="waiver_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="triproster",
            name="role",
            field=models.CharField(
                choices=[
                    ("DIVER", "Diver"),
                    ("DM", "Divemaster"),
                    ("INSTRUCTOR", "Instructor"),
                ],
                default="DIVER",
                help_text="Role on this trip (diver, divemaster, or instructor)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="triproster",
            index=models.Index(fields=["role"], name="diveops_tri_role_f37517_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "confirmed", "checked_in"])
                ),
                fields=("trip", "diver"),
                name="diveops_booking_one_active_per_trip",
            ),
        ),
        migrations.AddConstraint(
            model_name="diverprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_dives__gte", 0)),
                name="diveops_diver_total_dives_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_depth_meters__gt", 0)),
                name="diveops_site_depth_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="diveops_site_valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="diveops_site_valid_longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="divetrip",
            constraint=models.CheckConstraint(
                condition=models.Q(("return_time__gt", models.F("departure_time"))),
                name="diveops_trip_return_after_departure",
            ),
        ),
        migrations.AddConstraint(
            model_name="divetrip",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_divers__gt", 0)),
                name="diveops_trip_max_divers_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="divetrip",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_per_diver__gte", 0)),
                name="diveops_trip_price_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="triproster",
            constraint=models.UniqueConstraint(
                fields=("trip", "diver"), name="diveops_roster_one_per_trip"
            ),
        ),
    ]
