# Generated by Django 6.0 on 2026-01-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excursion",
            name="dive_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary dive site (optional - sites can be set per dive)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="excursions",
                to="diveops.divesite",
            ),
        ),
    ]
