# Generated by Django 6.0 on 2026-01-04 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0002_refactor_constraints_add_features"),
        ("django_parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code like 'ow', 'aow', 'dm'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name like 'Open Water Diver'", max_length=100
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Numeric rank for comparison (higher = more advanced)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rank"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rank__gt", 0)),
                        name="diveops_cert_level_rank_gt_zero",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiverCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certification_number", models.CharField(max_length=100)),
                ("certified_on", models.DateField()),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if certification never expires",
                        null=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        help_text="Certification agency (PADI, SSI, NAUI, etc.)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diver_certifications",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diver_certifications",
                        to="diveops.certificationlevel",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-level__rank", "-certified_on"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("diver", "level", "agency"),
                        name="diveops_unique_active_certification",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_on__isnull", True),
                            ("expires_on__gt", models.F("certified_on")),
                            _connector="OR",
                        ),
                        name="diveops_cert_expires_after_certified",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TripRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("certification", "Certification Level"),
                            ("medical", "Medical Clearance"),
                            ("gear", "Equipment/Gear"),
                            ("experience", "Dive Experience"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_dives",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum number of logged dives",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certification_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_requirements",
                        to="diveops.certificationlevel",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="diveops.divetrip",
                    ),
                ),
            ],
            options={
                "ordering": ["requirement_type"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("trip", "requirement_type"),
                        name="diveops_unique_requirement_type_per_trip",
                    )
                ],
            },
        ),
    ]
