# Generated by Django 6.0 on 2026-01-04 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0002_excursion_dive_site_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcursionType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "dive_mode",
                    models.CharField(
                        choices=[("boat", "Boat Dive"), ("shore", "Shore Dive")],
                        max_length=10,
                    ),
                ),
                (
                    "time_of_day",
                    models.CharField(
                        choices=[
                            ("day", "Day Dive"),
                            ("night", "Night Dive"),
                            ("dawn", "Dawn Dive"),
                            ("dusk", "Dusk Dive"),
                        ],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("max_depth_meters", models.PositiveIntegerField()),
                ("typical_duration_minutes", models.PositiveIntegerField(default=60)),
                ("dives_per_excursion", models.PositiveSmallIntegerField(default=2)),
                (
                    "requires_cert",
                    models.BooleanField(
                        default=True,
                        help_text="If False, no certification check (for DSD)",
                    ),
                ),
                (
                    "is_training",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this is a training/intro dive (DSD)",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price before site adjustments",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_certification_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Minimum certification required (null = no requirement)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excursion_types",
                        to="diveops.certificationlevel",
                    ),
                ),
                (
                    "suitable_sites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sites where this type can be run (empty = all sites)",
                        related_name="excursion_types",
                        to="diveops.divesite",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="diveops_exc_is_acti_6b2df3_idx"
                    ),
                    models.Index(
                        fields=["dive_mode"], name="diveops_exc_dive_mo_666e26_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("base_price__gte", 0)),
                        name="diveops_excursion_type_base_price_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_depth_meters__gt", 0)),
                        name="diveops_excursion_type_depth_gt_zero",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SitePriceAdjustment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("distance", "Distance/Fuel Surcharge"),
                            ("park_fee", "Park Entry Fee"),
                            ("night", "Night Dive Surcharge"),
                            ("boat", "Boat Charter Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Adjustment amount (added to base price)",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "applies_to_mode",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If set, only applies to this dive mode (boat/shore)",
                        max_length=10,
                    ),
                ),
                (
                    "is_per_diver",
                    models.BooleanField(
                        default=True,
                        help_text="If True, applied per diver; if False, applied per trip",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dive_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_adjustments",
                        to="diveops.divesite",
                    ),
                ),
            ],
            options={
                "ordering": ["dive_site", "kind"],
                "indexes": [
                    models.Index(
                        fields=["dive_site", "is_active"],
                        name="diveops_sit_dive_si_e85a74_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("dive_site", "kind"),
                        name="diveops_unique_site_adjustment_kind",
                    )
                ],
            },
        ),
    ]
