# Generated by Django 6.0 on 2026-01-04 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0003_excursion_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursion",
            name="excursion_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Product type template (for pricing and eligibility)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="excursions",
                to="diveops.excursiontype",
            ),
        ),
    ]
