# Generated by Django 6.0 on 2026-01-04 01:54
# Manually modified to handle data migration

import django.db.models.deletion
from django.db import migrations, models


def create_certification_agencies(apps, schema_editor):
    """Create Organization records for certification agencies."""
    Organization = apps.get_model("django_parties", "Organization")

    agencies = [
        {"name": "PADI", "legal_name": "Professional Association of Diving Instructors", "org_type": "certification_agency"},
        {"name": "SSI", "legal_name": "Scuba Schools International", "org_type": "certification_agency"},
        {"name": "NAUI", "legal_name": "National Association of Underwater Instructors", "org_type": "certification_agency"},
        {"name": "SDI", "legal_name": "Scuba Diving International", "org_type": "certification_agency"},
        {"name": "BSAC", "legal_name": "British Sub-Aqua Club", "org_type": "certification_agency"},
        {"name": "CMAS", "legal_name": "Confédération Mondiale des Activités Subaquatiques", "org_type": "certification_agency"},
    ]

    for agency_data in agencies:
        Organization.objects.get_or_create(
            name=agency_data["name"],
            defaults={
                "legal_name": agency_data["legal_name"],
                "org_type": agency_data["org_type"],
            }
        )


def migrate_agency_data(apps, schema_editor):
    """Convert existing text-based certification_agency to FK references."""
    DiverProfile = apps.get_model("diveops", "DiverProfile")
    Organization = apps.get_model("django_parties", "Organization")

    # Get or create a default PADI organization for unmapped agencies
    default_agency, _ = Organization.objects.get_or_create(
        name="PADI",
        defaults={"org_type": "certification_agency"}
    )

    # Mapping of common text variations to Organization names
    agency_mapping = {
        "padi": "PADI",
        "p.a.d.i.": "PADI",
        "ssi": "SSI",
        "naui": "NAUI",
        "sdi": "SDI",
        "bsac": "BSAC",
        "cmas": "CMAS",
    }

    for profile in DiverProfile.objects.all():
        # Get the old text value (stored in certification_agency_old temporarily)
        old_value = getattr(profile, "_certification_agency_text", None)
        if old_value:
            normalized = old_value.lower().strip()
            org_name = agency_mapping.get(normalized, old_value.upper())

            org, _ = Organization.objects.get_or_create(
                name=org_name,
                defaults={"org_type": "certification_agency"}
            )
            profile.certification_agency_id = org.id
            profile.save()


def reverse_migrate_agency_data(apps, schema_editor):
    """Reverse migration - convert FK back to text (best effort)."""
    pass  # Can't fully reverse, would need to store original text


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0003_add_certification_models"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        # Step 1: Create certification agencies as Organizations
        migrations.RunPython(create_certification_agencies, migrations.RunPython.noop),

        # Step 2: Rename old field temporarily
        migrations.RenameField(
            model_name="diverprofile",
            old_name="certification_agency",
            new_name="certification_agency_old",
        ),

        # Step 3: Add new FK field (nullable at first)
        migrations.AddField(
            model_name="diverprofile",
            name="certification_agency",
            field=models.ForeignKey(
                null=True,  # Temporarily nullable
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diver_profiles",
                to="django_parties.organization",
                help_text="Certification agency (PADI, SSI, NAUI, etc.)",
            ),
        ),

        # Step 4: Migrate data from old text field to new FK
        migrations.RunPython(
            code=lambda apps, schema_editor: _migrate_existing_data(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 5: Remove old text field
        migrations.RemoveField(
            model_name="diverprofile",
            name="certification_agency_old",
        ),

        # Step 6: Make FK non-nullable
        migrations.AlterField(
            model_name="diverprofile",
            name="certification_agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diver_profiles",
                to="django_parties.organization",
                help_text="Certification agency (PADI, SSI, NAUI, etc.)",
            ),
        ),
    ]


def _migrate_existing_data(apps, schema_editor):
    """Convert existing text-based certification_agency to FK references."""
    DiverProfile = apps.get_model("diveops", "DiverProfile")
    Organization = apps.get_model("django_parties", "Organization")

    # Get or create a default PADI organization for unmapped agencies
    default_agency, _ = Organization.objects.get_or_create(
        name="PADI",
        defaults={"org_type": "certification_agency"}
    )

    # Mapping of common text variations to Organization names
    agency_mapping = {
        "padi": "PADI",
        "p.a.d.i.": "PADI",
        "ssi": "SSI",
        "naui": "NAUI",
        "sdi": "SDI",
        "bsac": "BSAC",
        "cmas": "CMAS",
    }

    for profile in DiverProfile.objects.all():
        old_value = profile.certification_agency_old
        if old_value:
            normalized = old_value.lower().strip()
            org_name = agency_mapping.get(normalized, old_value.upper())

            org, _ = Organization.objects.get_or_create(
                name=org_name,
                defaults={"org_type": "certification_agency"}
            )
            profile.certification_agency = org
            profile.save()
        else:
            # Use default agency if no value
            profile.certification_agency = default_agency
            profile.save()
