# Generated by Django 6.0 on 2026-01-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0004_excursion_type_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="divesite",
            name="dive_mode",
            field=models.CharField(
                choices=[
                    ("boat", "Boat Accessible"),
                    ("shore", "Shore Accessible"),
                    ("cenote", "Cenote"),
                    ("cavern", "Cavern/Cave"),
                ],
                default="boat",
                help_text="How this site is accessed (boat, shore, cenote, cavern)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="excursiontype",
            name="dive_mode",
            field=models.CharField(
                choices=[
                    ("boat", "Boat Dive"),
                    ("shore", "Shore Dive"),
                    ("cenote", "Cenote Dive"),
                    ("cavern", "Cavern/Cave Dive"),
                ],
                max_length=10,
            ),
        ),
    ]
