# Generated by Django 6.0 on 2026-01-04 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0005_add_agency_to_cert_level_and_proof_document"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificationlevel",
            name="agency",
            field=models.ForeignKey(
                help_text="Certification agency that defines this level (PADI, SSI, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certification_levels",
                to="django_parties.organization",
            ),
        ),
        migrations.AlterField(
            model_name="diverprofile",
            name="certification_agency",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use DiverCertification model instead",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diver_profiles",
                to="django_parties.organization",
            ),
        ),
        migrations.AlterField(
            model_name="diverprofile",
            name="certification_date",
            field=models.DateField(
                blank=True,
                help_text="DEPRECATED: Use DiverCertification model instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="diverprofile",
            name="certification_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sd", "Scuba Diver"),
                    ("ow", "Open Water"),
                    ("aow", "Advanced Open Water"),
                    ("rescue", "Rescue Diver"),
                    ("dm", "Divemaster"),
                    ("instructor", "Instructor"),
                ],
                default="",
                help_text="DEPRECATED: Use DiverCertification model instead",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="diverprofile",
            name="certification_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DEPRECATED: Use DiverCertification model instead",
                max_length=100,
            ),
        ),
    ]
