# Generated by Django 6.0 on 2026-01-05 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0005_add_dive_mode_to_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcursionTypeDive",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        help_text="Dive number within the excursion (1, 2, 3...)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this dive (e.g., 'First Tank', 'Deep Dive')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description or notes about this dive"
                    ),
                ),
                (
                    "planned_depth_meters",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Target maximum depth in meters",
                        null=True,
                    ),
                ),
                (
                    "planned_duration_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Planned dive duration in minutes",
                        null=True,
                    ),
                ),
                (
                    "offset_minutes",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Minutes after excursion departure that this dive starts",
                    ),
                ),
                (
                    "excursion_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dive_templates",
                        to="diveops.excursiontype",
                    ),
                ),
                (
                    "min_certification_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific certification for this dive (overrides excursion type if set)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dive_templates",
                        to="diveops.certificationlevel",
                    ),
                ),
            ],
            options={
                "ordering": ["excursion_type", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["excursion_type", "sequence"],
                        name="diveops_exc_excursi_0cd47e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("excursion_type", "sequence"),
                        name="diveops_excursion_type_dive_unique_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="diveops_excursion_type_dive_sequence_gte_1",
                    ),
                ],
            },
        ),
    ]
