# Generated by Django 6.0 on 2026-01-05
# T-001: Price Immutability - Add price snapshot fields to Booking

from django.db import migrations, models


class Migration(migrations.Migration):
    """T-001: Price Immutability.

    INV-3: Price is snapshotted at booking creation.
    - price_snapshot (JSONField) stores full pricing context
    - price_amount/price_currency are denormalized for queries
    - Price is NOT recomputed when pricing rules change
    """

    dependencies = [
        ("diveops", "0006_add_excursion_type_dive"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price_snapshot",
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="Full pricing context at booking time (immutable snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="price_amount",
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                max_digits=10,
                help_text="Price locked at booking (denormalized from snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="price_currency",
            field=models.CharField(
                blank=True,
                default="",
                max_length=3,
                help_text="Currency code (denormalized from snapshot)",
            ),
        ),
    ]
