# Generated by Django 6.0 on 2026-01-05 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0007_booking_price_snapshot"),
        ("django_ledger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[("revenue", "Revenue"), ("refund", "Refund")],
                        default="revenue",
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Deterministic key: {booking_id}:{type}:{sequence}",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Settlement amount", max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "settled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the settlement was recorded",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="diveops.booking",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processed_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked ledger transaction (immutable after posting)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diveops_settlements",
                        to="django_ledger.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-settled_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "settlement_type"],
                        name="diveops_set_booking_8a455a_idx",
                    ),
                    models.Index(
                        fields=["settled_at"], name="diveops_set_settled_e60b56_idx"
                    ),
                ],
            },
        ),
    ]
