# Generated by Django 6.0 on 2026-01-05 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0008_settlement_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityOverride",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requirement_type",
                    models.CharField(
                        help_text="Type of requirement bypassed (certification, experience, medical, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "original_requirement",
                    models.JSONField(
                        help_text="Original requirement that was bypassed (for audit trail)"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Justification for the override (required)"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eligibility_overrides_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_override",
                        to="diveops.booking",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eligibility_overrides",
                        to="diveops.diverprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-approved_at"],
                "indexes": [
                    models.Index(
                        fields=["booking"], name="diveops_eli_booking_281082_idx"
                    ),
                    models.Index(
                        fields=["diver"], name="diveops_eli_diver_i_c9612a_idx"
                    ),
                    models.Index(
                        fields=["approved_at"], name="diveops_eli_approve_b4b158_idx"
                    ),
                ],
            },
        ),
    ]
