# Generated by Django 6.0 on 2026-01-05 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0009_eligibility_override"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g., 15.00 = 15%) or fixed amount (e.g., 25.00)",
                        max_digits=10,
                    ),
                ),
                (
                    "effective_at",
                    models.DateTimeField(
                        help_text="When this rule becomes effective. Latest effective_at <= as_of wins."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Reason for this rate or notes about the rule",
                    ),
                ),
                (
                    "dive_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_rules",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "excursion_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, rule only applies to this ExcursionType. NULL = shop default.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_rules",
                        to="diveops.excursiontype",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_at"],
                "indexes": [
                    models.Index(
                        fields=["dive_shop", "excursion_type", "effective_at"],
                        name="diveops_com_dive_sh_09c358_idx",
                    ),
                    models.Index(
                        fields=["effective_at"], name="diveops_com_effecti_d86ddc_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rate_value__gte", 0)),
                        name="diveops_commission_rate_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("rate_type", "percentage"), _negated=True),
                            ("rate_value__lte", 100),
                            _connector="OR",
                        ),
                        name="diveops_commission_percentage_max_100",
                    ),
                ],
            },
        ),
    ]
