# Generated by Django 6.0 on 2026-01-05 14:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0010_commission_rule"),
        ("django_ledger", "0001_initial"),
        ("django_parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period_start",
                    models.DateTimeField(
                        help_text="Start of period for eligible bookings"
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        help_text="End of period for eligible bookings"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_bookings",
                    models.IntegerField(
                        default=0, help_text="Total eligible bookings found"
                    ),
                ),
                (
                    "settled_count",
                    models.IntegerField(
                        default=0, help_text="Number of bookings successfully settled"
                    ),
                ),
                (
                    "failed_count",
                    models.IntegerField(
                        default=0, help_text="Number of bookings that failed to settle"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount settled in this run",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "run_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the run was executed"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the run finished", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Details of any failures during the run",
                    ),
                ),
                (
                    "dive_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_runs",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_runs_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-run_at"],
            },
        ),
        migrations.AddField(
            model_name="settlementrecord",
            name="settlement_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Settlement run this record belongs to (if batch processed)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settlements",
                to="diveops.settlementrun",
            ),
        ),
        migrations.AddIndex(
            model_name="settlementrecord",
            index=models.Index(
                fields=["settlement_run"], name="diveops_set_settlem_7719bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlementrun",
            index=models.Index(
                fields=["dive_shop", "run_at"], name="diveops_set_dive_sh_048777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlementrun",
            index=models.Index(fields=["status"], name="diveops_set_status_ab20da_idx"),
        ),
    ]
