# Generated by Django 6.0 on 2026-01-05 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0011_settlement_run"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiveAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("diver", "Diver"),
                            ("guide", "Guide"),
                            ("instructor", "Instructor"),
                            ("student", "Student"),
                        ],
                        default="diver",
                        max_length=20,
                    ),
                ),
                (
                    "planned_max_depth",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Planned max depth for this diver (overrides dive plan)",
                        null=True,
                    ),
                ),
                (
                    "planned_bottom_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Planned bottom time for this diver (overrides dive plan)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("briefed", "Briefed"),
                            ("gearing_up", "Gearing Up"),
                            ("in_water", "In Water"),
                            ("surfaced", "Surfaced"),
                            ("on_boat", "On Boat"),
                            ("sat_out", "Sat Out"),
                            ("aborted", "Aborted"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "entered_water_at",
                    models.DateTimeField(
                        blank=True, help_text="When diver entered the water", null=True
                    ),
                ),
                (
                    "surfaced_at",
                    models.DateTimeField(
                        blank=True, help_text="When diver surfaced", null=True
                    ),
                ),
                (
                    "last_known_bearing",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Last known compass bearing (for tracking)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["dive", "role", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiveLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buddy_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Buddy name (if not in system or for display)",
                        max_length=100,
                    ),
                ),
                (
                    "max_depth_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Personal max depth (null = use dive value)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "bottom_time_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Personal bottom time (null = use dive value)",
                        null=True,
                    ),
                ),
                (
                    "air_start_bar",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Starting tank pressure in bar", null=True
                    ),
                ),
                (
                    "air_end_bar",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Ending tank pressure in bar", null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Weight used in kg",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "suit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("shorty", "Shorty"),
                            ("3mm", "3mm"),
                            ("5mm", "5mm"),
                            ("7mm", "7mm"),
                            ("dry", "Drysuit"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "tank_size_liters",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Tank size in liters", null=True
                    ),
                ),
                (
                    "nitrox_percentage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nitrox O2 percentage (21-40 for recreational)",
                        null=True,
                    ),
                ),
                (
                    "computer_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw dive computer import payload",
                        null=True,
                    ),
                ),
                (
                    "computer_max_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Max depth from dive computer",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "computer_avg_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Average depth from dive computer",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "computer_bottom_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Bottom time from dive computer",
                        null=True,
                    ),
                ),
                (
                    "computer_dive_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Total dive time from dive computer",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "dive_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Diver's sequential dive number (auto-assigned or manual)",
                        null=True,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When the log was verified", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("shop", "Shop System"), ("manual", "Manual Entry")],
                        default="shop",
                        help_text="How this log was created",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-dive__planned_start"],
            },
        ),
        migrations.AddField(
            model_name="dive",
            name="current",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("mild", "Mild"),
                    ("moderate", "Moderate"),
                    ("strong", "Strong"),
                ],
                default="",
                help_text="Current strength during dive",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="logged_at",
            field=models.DateTimeField(
                blank=True, help_text="When the dive results were logged", null=True
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="logged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who logged the dive results",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dives_logged",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="surface_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calm", "Calm"),
                    ("slight", "Slight"),
                    ("moderate", "Moderate"),
                    ("rough", "Rough"),
                ],
                default="",
                help_text="Surface water conditions",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="visibility_meters",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Underwater visibility in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="water_temp_celsius",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Water temperature in Celsius",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="dive",
            index=models.Index(
                fields=["logged_at"], name="diveops_div_logged__7de235_idx"
            ),
        ),
        migrations.AddField(
            model_name="diveassignment",
            name="buddy",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned buddy for this dive",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buddy_assignments",
                to="diveops.diverprofile",
            ),
        ),
        migrations.AddField(
            model_name="diveassignment",
            name="dive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="diveops.dive",
            ),
        ),
        migrations.AddField(
            model_name="diveassignment",
            name="diver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_assignments",
                to="diveops.diverprofile",
            ),
        ),
        migrations.AddField(
            model_name="divelog",
            name="assignment",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to assignment (expected when created through ops)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dive_log",
                to="diveops.diveassignment",
            ),
        ),
        migrations.AddField(
            model_name="divelog",
            name="buddy",
            field=models.ForeignKey(
                blank=True,
                help_text="Buddy profile (if in system)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buddy_logs",
                to="diveops.diverprofile",
            ),
        ),
        migrations.AddField(
            model_name="divelog",
            name="dive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_logs",
                to="diveops.dive",
            ),
        ),
        migrations.AddField(
            model_name="divelog",
            name="diver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_logs",
                to="diveops.diverprofile",
            ),
        ),
        migrations.AddField(
            model_name="divelog",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff who verified this log",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dive_logs_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="diveassignment",
            index=models.Index(
                fields=["dive", "status"], name="diveops_div_dive_id_4ca3d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diveassignment",
            index=models.Index(fields=["diver"], name="diveops_div_diver_i_baee94_idx"),
        ),
        migrations.AddConstraint(
            model_name="diveassignment",
            constraint=models.UniqueConstraint(
                fields=("dive", "diver"), name="diveops_dive_assignment_unique_diver"
            ),
        ),
        migrations.AddIndex(
            model_name="divelog",
            index=models.Index(
                fields=["diver", "dive"], name="diveops_div_diver_i_a606cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="divelog",
            index=models.Index(
                fields=["verified_at"], name="diveops_div_verifie_d75d68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="divelog",
            index=models.Index(
                fields=["dive_number"], name="diveops_div_dive_nu_39c258_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="divelog",
            constraint=models.UniqueConstraint(
                fields=("dive", "diver"), name="diveops_dive_log_unique_diver"
            ),
        ),
        migrations.AddConstraint(
            model_name="divelog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("air_start_bar__isnull", True),
                    ("air_end_bar__isnull", True),
                    ("air_end_bar__lt", models.F("air_start_bar")),
                    _connector="OR",
                ),
                name="diveops_dive_log_air_end_lt_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="divelog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("nitrox_percentage__isnull", True),
                    models.Q(
                        ("nitrox_percentage__gte", 21), ("nitrox_percentage__lte", 40)
                    ),
                    _connector="OR",
                ),
                name="diveops_dive_log_nitrox_21_40",
            ),
        ),
    ]
