# Generated by Django 6.0 on 2026-01-05 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0012_dive_log_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dive",
            name="plan_locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the plan was locked (briefing sent)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="plan_locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who locked the plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="plan_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Frozen copy of plan at time of briefing lock",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="plan_snapshot_outdated",
            field=models.BooleanField(
                default=False,
                help_text="True if planned fields changed after lock (needs resend)",
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="plan_template_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID of ExcursionTypeDive template used for snapshot",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="plan_template_published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the source template was published",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="briefing_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full briefing content for communication to divers",
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="equipment_requirements",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Equipment requirements by category: {required: [], recommended: [], rental_available: []}",
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="gas",
            field=models.CharField(
                blank=True,
                choices=[
                    ("air", "Air"),
                    ("ean32", "EAN32"),
                    ("ean36", "EAN36"),
                    ("trimix", "Trimix"),
                ],
                default="",
                help_text="Gas mix for this dive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="hazards",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Known hazards and safety considerations",
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="retired_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who retired this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="route",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Dive profile, route description, or navigation plan",
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Skills to practice (for training dives)",
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("retired", "Retired"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="dive",
            index=models.Index(
                fields=["plan_locked_at"], name="diveops_div_plan_lo_970304_idx"
            ),
        ),
    ]
