# Generated by Django 6.0 on 2026-01-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0013_dive_plan_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursiontypedive",
            name="route_segments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured dive profile: [{phase, depth_m, duration_min, description}, ...]",
            ),
        ),
    ]
