# Generated by Django 6.0 on 2026-01-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0014_route_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursiontypedive",
            name="dive_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific site this plan is for (null = generic template)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_plan_templates",
                to="diveops.divesite",
            ),
        ),
    ]
