# Generated by Django 6.0 on 2026-01-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0017_diver_equipment_rental_unique"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="diverequipmentrental",
            new_name="diveops_div_booking_1347f9_idx",
            old_name="diveops_div_booking_4af8e7_idx",
        ),
        migrations.RenameIndex(
            model_name="diverequipmentrental",
            new_name="diveops_div_rented__7693ca_idx",
            old_name="diveops_div_rented__09a009_idx",
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="surface_interval_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Surface interval before this dive (minutes). Null for first dive.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="diverequipmentrental",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
