# Generated by Django 6.0 on 2026-01-06 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0018_add_surface_interval_to_excursion_type_dive"),
        ("django_parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Standard Liability Release')",
                        max_length=100,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("waiver", "Liability Waiver"),
                            ("medical", "Medical Questionnaire"),
                            ("briefing", "Briefing Acknowledgment"),
                            ("code_of_conduct", "Diver Code of Conduct"),
                            ("rental", "Equipment Rental Agreement"),
                            ("training", "Training Agreement"),
                            ("other", "Other"),
                        ],
                        help_text="Type of agreement this template is for",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Internal description or notes about this template",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The agreement text/content (supports HTML)"
                    ),
                ),
                (
                    "requires_signature",
                    models.BooleanField(
                        default=True, help_text="Does this form require a signature?"
                    ),
                ),
                (
                    "requires_initials",
                    models.BooleanField(
                        default=False,
                        help_text="Does this form require initials on each page/section?",
                    ),
                ),
                (
                    "is_required_for_booking",
                    models.BooleanField(
                        default=False,
                        help_text="Must this form be signed before diving?",
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many days this agreement is valid (null = never expires)",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Version number of this template",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dive_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_templates",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["dive_shop", "template_type", "-version"],
                "indexes": [
                    models.Index(
                        fields=["dive_shop", "template_type"],
                        name="diveops_agr_dive_sh_979f10_idx",
                    ),
                    models.Index(
                        fields=["status"], name="diveops_agr_status_d19cec_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status", "published"), ("deleted_at__isnull", True)
                        ),
                        fields=("dive_shop", "template_type"),
                        name="diveops_unique_published_template_per_type",
                    )
                ],
            },
        ),
    ]
