# Generated by Django 6.0 on 2026-01-06 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0019_add_agreement_template"),
        ("django_catalog", "0002_add_catalogitemcomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursiontype",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Default product sold for this excursion type.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="excursion_types",
                to="django_catalog.catalogitem",
            ),
        ),
    ]
