# Generated by Django 6.0 on 2026-01-06 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0020_add_excursiontype_catalog_item"),
        ("django_catalog", "0002_add_catalogitemcomponent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="excursiontype",
            name="catalog_item",
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Product sold for this dive (includes components like tank, weights, etc.).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_plan_templates",
                to="django_catalog.catalogitem",
            ),
        ),
    ]
