# Generated by Django 6.0 on 2026-01-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0021_move_catalog_item_to_dive_template"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="excursiontype",
            name="diveops_excursion_type_depth_gt_zero",
        ),
        migrations.RemoveField(
            model_name="excursiontype",
            name="max_depth_meters",
        ),
    ]
