# Generated by Django 6.0 on 2026-01-06 04:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0022_remove_excursiontype_max_depth"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiveSegmentType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Segment type name (e.g., 'descent', 'level', 'wreck_exploration')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Descent', 'Level Section', 'Wreck Exploration')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this segment type"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue",
                        help_text="Color for UI display (tailwind color name: blue, green, yellow, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "is_depth_transition",
                    models.BooleanField(
                        default=False,
                        help_text="True for descent/ascent segments that have from/to depths",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Order in dropdown menus (lower = first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="excursiontypedive",
            options={
                "ordering": ["excursion_type", "sequence"],
                "verbose_name": "Dive Plan Template",
                "verbose_name_plural": "Dive Plan Templates",
            },
        ),
    ]
