# Generated by Django 6.0 on 2026-01-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0024_seed_dive_segment_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excursiontypedive",
            name="excursion_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional - link to an excursion type to use this plan as a template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dive_templates",
                to="diveops.excursiontype",
            ),
        ),
    ]
