# Generated by Django 6.0 on 2026-01-06 04:56

from django.conf import settings
from django.db import migrations, models


def migrate_excursion_type_to_m2m(apps, schema_editor):
    """Copy excursion_type FK values to excursion_types M2M field."""
    ExcursionTypeDive = apps.get_model("diveops", "ExcursionTypeDive")
    for dive in ExcursionTypeDive.objects.filter(excursion_type__isnull=False):
        dive.excursion_types.add(dive.excursion_type)


def migrate_excursion_types_to_fk(apps, schema_editor):
    """Reverse: copy first excursion_types M2M value back to excursion_type FK."""
    ExcursionTypeDive = apps.get_model("diveops", "ExcursionTypeDive")
    for dive in ExcursionTypeDive.objects.all():
        first_type = dive.excursion_types.first()
        if first_type:
            dive.excursion_type = first_type
            dive.save(update_fields=["excursion_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0025_make_dive_plan_excursion_type_optional"),
        ("django_catalog", "0002_add_catalogitemcomponent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="excursiontypedive",
            options={
                "ordering": ["sequence", "name"],
                "verbose_name": "Dive Plan Template",
                "verbose_name_plural": "Dive Plan Templates",
            },
        ),
        migrations.RemoveConstraint(
            model_name="excursiontypedive",
            name="diveops_excursion_type_dive_unique_sequence",
        ),
        migrations.RemoveIndex(
            model_name="excursiontypedive",
            name="diveops_exc_excursi_0cd47e_idx",
        ),
        # Add M2M field first (before data migration)
        migrations.AddField(
            model_name="excursiontypedive",
            name="excursion_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Excursion types that use this dive plan template",
                related_name="dive_templates",
                to="diveops.excursiontype",
            ),
        ),
        # Migrate data from FK to M2M
        migrations.RunPython(migrate_excursion_type_to_m2m, migrate_excursion_types_to_fk),
        # Now safe to remove the FK field
        migrations.RemoveField(
            model_name="excursiontypedive",
            name="excursion_type",
        ),
        migrations.AddIndex(
            model_name="excursiontypedive",
            index=models.Index(
                fields=["sequence"], name="diveops_exc_sequenc_54ae88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excursiontypedive",
            index=models.Index(
                fields=["dive_site"], name="diveops_exc_dive_si_3e7fa1_idx"
            ),
        ),
    ]
