# Generated by Django 6.0 on 2026-01-06 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0026_dive_plan_many_excursion_types"),
        ("django_catalog", "0002_add_catalogitemcomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursiontype",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Catalog item representing this excursion type product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excursion_types",
                to="django_catalog.catalogitem",
            ),
        ),
    ]
