# Generated by Django 6.0 on 2026-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0027_add_excursiontype_catalog_item_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursiontypedive",
            name="briefing_video_url",
            field=models.URLField(
                blank=True, default="", help_text="YouTube video URL for dive briefing"
            ),
        ),
    ]
