# Generated by Django 6.0 on 2026-01-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0028_add_briefing_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="excursiontypedive",
            name="access_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boat", "Boat"),
                    ("vehicle", "Vehicle Transport"),
                    ("beach_meet", "Meet at Beach"),
                    ("shore_walk", "Shore Walk-In"),
                    ("dock", "Dock Entry"),
                ],
                default="",
                help_text="How divers get to the dive site",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="excursiontypedive",
            name="boat_instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Instructions for boat dives (boarding, gear storage, entry/exit procedures)",
            ),
        ),
    ]
