# Generated by Django 6.0 on 2026-01-06 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0029_add_access_mode_and_boat_instructions"),
        ("django_agreements", "0001_initial"),
        ("django_catalog", "0002_add_catalogitemcomponent"),
        ("django_documents", "0001_initial"),
        ("django_geo", "0003_place_place_valid_latitude_and_more"),
        ("django_parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VesselPermit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("vessel_name", models.CharField(max_length=100)),
                ("vessel_registration", models.CharField(blank=True, max_length=50)),
                ("permit_number", models.CharField(max_length=50)),
                ("issued_at", models.DateField()),
                ("expires_at", models.DateField()),
                ("max_divers", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["marine_park", "vessel_name"],
            },
        ),
        migrations.CreateModel(
            name="DiverEligibilityProof",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("student_id", "Student ID"),
                            ("national_id", "National ID (INE/IFE)"),
                            ("resident_card", "Resident Card"),
                            ("local_address", "Local Address Proof"),
                            ("passport", "Passport"),
                            ("birth_cert", "Birth Certificate"),
                            ("senior_id", "Senior ID (INAPAM)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_proofs",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eligibility_proofs",
                        to="django_documents.document",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_eligibility_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarinePark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "boundary_file",
                    models.FileField(
                        blank=True, null=True, upload_to="marine_parks/boundaries/%Y/"
                    ),
                ),
                ("boundary_filename", models.CharField(blank=True, max_length=255)),
                ("governing_authority", models.CharField(blank=True, max_length=200)),
                ("authority_contact", models.TextField(blank=True)),
                ("official_website", models.URLField(blank=True)),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "designation_type",
                    models.CharField(
                        choices=[
                            ("national_park", "National Park"),
                            ("marine_reserve", "Marine Reserve"),
                            ("biosphere_reserve", "Biosphere Reserve"),
                            ("protected_area", "Protected Natural Area"),
                            ("sanctuary", "Marine Sanctuary"),
                        ],
                        default="protected_area",
                        max_length=50,
                    ),
                ),
                (
                    "max_divers_per_site",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marine_parks",
                        to="django_geo.place",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="divesite",
            name="marine_park",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_sites",
                to="diveops.marinepark",
            ),
        ),
        migrations.CreateModel(
            name="ParkFeeSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Diver Admission 2024'", max_length=100
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("per_person", "Per Person"),
                            ("per_boat", "Per Boat"),
                            ("per_trip", "Per Trip"),
                            ("per_day", "Per Day"),
                            ("per_activity", "Per Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("diving", "Diving"),
                            ("snorkeling", "Snorkeling"),
                            ("kayaking", "Kayaking"),
                            ("fishing", "Fishing"),
                            ("all", "All Activities"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_start", models.DateField()),
                ("effective_end", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="MXN", max_length=3)),
                (
                    "collector",
                    models.CharField(
                        blank=True,
                        help_text="Who collects this fee (e.g., 'CONANP', 'Dive Shop')",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catalog item for auto-adding to pricing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="park_fee_schedules",
                        to="django_catalog.catalogitem",
                    ),
                ),
                (
                    "marine_park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_schedules",
                        to="diveops.marinepark",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_start", "name"],
            },
        ),
        migrations.CreateModel(
            name="ParkFeeTier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tier_code",
                    models.CharField(
                        choices=[
                            ("tourist", "Tourist (Foreign)"),
                            ("national", "National"),
                            ("local", "Local Resident"),
                            ("student", "Student"),
                            ("senior", "Senior"),
                            ("child", "Child"),
                            ("infant", "Infant (Free)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(help_text="Display label", max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("age_min", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age_max", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("requires_proof", models.BooleanField(default=False)),
                (
                    "proof_notes",
                    models.TextField(
                        blank=True,
                        help_text="What proof is needed (e.g., 'INE card', 'Student ID')",
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="diveops.parkfeeschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "tier_code"],
            },
        ),
        migrations.CreateModel(
            name="ParkZone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField()),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("core", "Core Zone (No-Take)"),
                            ("buffer", "Buffer Zone"),
                            ("use", "Use Zone (Recreational)"),
                            ("restoration", "Restoration Zone"),
                            ("research", "Research Zone"),
                        ],
                        default="use",
                        max_length=20,
                    ),
                ),
                (
                    "boundary_file",
                    models.FileField(
                        blank=True, null=True, upload_to="marine_parks/zones/%Y/"
                    ),
                ),
                (
                    "boundary_geojson",
                    models.JSONField(
                        blank=True,
                        help_text="GeoJSON geometry for zone boundary (optional, manual entry)",
                        null=True,
                    ),
                ),
                ("max_divers", models.PositiveIntegerField(blank=True, null=True)),
                ("diving_allowed", models.BooleanField(default=True)),
                ("anchoring_allowed", models.BooleanField(default=False)),
                ("fishing_allowed", models.BooleanField(default=False)),
                ("requires_guide", models.BooleanField(default=True)),
                ("requires_permit", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "marine_park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="diveops.marinepark",
                    ),
                ),
            ],
            options={
                "ordering": ["marine_park", "name"],
            },
        ),
        migrations.CreateModel(
            name="ParkRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("max_depth", "Maximum Depth"),
                            ("max_divers", "Maximum Divers"),
                            ("certification", "Certification Required"),
                            ("equipment", "Equipment Requirement"),
                            ("time", "Time Restriction"),
                            ("activity", "Activity Restriction"),
                            ("conduct", "Code of Conduct"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("diver", "Individual Diver"),
                            ("group", "Dive Group"),
                            ("vessel", "Vessel"),
                            ("operator", "Operator/Shop"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("diving", "Diving"),
                            ("snorkeling", "Snorkeling"),
                            ("boating", "Boating"),
                            ("training", "Training"),
                            ("all", "All Activities"),
                        ],
                        default="all",
                        help_text="Which activity this rule applies to",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="What the rule governs (e.g., 'night diving', 'spearfishing')",
                        max_length=100,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lte", "Less than or equal (<=)"),
                            ("gte", "Greater than or equal (>=)"),
                            ("eq", "Equals (=)"),
                            ("in", "In list"),
                            ("contains", "Contains"),
                            ("required_true", "Must be true"),
                        ],
                        default="",
                        help_text="Comparison operator for rule evaluation",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Value for comparison (e.g., '18' for max_depth lte 18)",
                        max_length=100,
                    ),
                ),
                ("details", models.TextField(blank=True, help_text="Full rule text")),
                ("effective_start", models.DateField()),
                ("effective_end", models.DateField(blank=True, null=True)),
                (
                    "enforcement_level",
                    models.CharField(
                        choices=[
                            ("info", "Information Only"),
                            ("warn", "Warning (Allow Override)"),
                            ("block", "Block (Hard Enforcement)"),
                        ],
                        default="warn",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "marine_park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="diveops.marinepark",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Official document defining this rule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="park_rules",
                        to="django_documents.document",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = applies park-wide",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="diveops.parkzone",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_start", "rule_type"],
            },
        ),
        migrations.CreateModel(
            name="ParkGuideCredential",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("credential_number", models.CharField(blank=True, max_length=50)),
                ("issued_at", models.DateField()),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("carta_eval_signed_at", models.DateField(blank=True, null=True)),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False,
                        help_text="True if this guide is also the boat owner",
                    ),
                ),
                (
                    "last_refresher_at",
                    models.DateField(
                        blank=True,
                        help_text="Date of last park refresher course",
                        null=True,
                    ),
                ),
                (
                    "next_refresher_due_at",
                    models.DateField(
                        blank=True, help_text="When next refresher is due", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True)),
                (
                    "carta_eval_agreement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Signed carta evaluación document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guide_carta_evals",
                        to="django_agreements.agreement",
                    ),
                ),
                (
                    "carta_eval_signed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Boat owner who signed (can be the guide themselves)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_carta_evals",
                        to="django_parties.person",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        help_text="Person receiving credential (must be DM or higher)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="park_guide_credentials",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "marine_park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_credentials",
                        to="diveops.marinepark",
                    ),
                ),
                (
                    "authorized_zones",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Zones this credential authorizes (empty = all zones)",
                        related_name="authorized_guides",
                        to="diveops.parkzone",
                    ),
                ),
            ],
            options={
                "ordering": ["marine_park", "diver"],
            },
        ),
        migrations.AddField(
            model_name="parkfeeschedule",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = applies park-wide",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_schedules",
                to="diveops.parkzone",
            ),
        ),
        migrations.AddField(
            model_name="divesite",
            name="park_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_sites",
                to="diveops.parkzone",
            ),
        ),
        migrations.AddIndex(
            model_name="divesite",
            index=models.Index(
                fields=["marine_park"], name="diveops_div_marine__ff6d95_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="divesite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("park_zone__isnull", True),
                    ("marine_park__isnull", False),
                    _connector="OR",
                ),
                name="diveops_site_zone_requires_park",
            ),
        ),
        migrations.AddField(
            model_name="vesselpermit",
            name="marine_park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vessel_permits",
                to="diveops.marinepark",
            ),
        ),
        migrations.AddField(
            model_name="vesselpermit",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vessel_permits",
                to="django_parties.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="divereligibilityproof",
            index=models.Index(
                fields=["diver", "status"], name="diveops_div_diver_i_c448ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="divereligibilityproof",
            index=models.Index(
                fields=["proof_type"], name="diveops_div_proof_t_67c43d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="divereligibilityproof",
            index=models.Index(
                fields=["expires_at"], name="diveops_div_expires_fafb2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marinepark",
            index=models.Index(fields=["code"], name="diveops_mar_code_d09bd9_idx"),
        ),
        migrations.AddIndex(
            model_name="marinepark",
            index=models.Index(
                fields=["is_active"], name="diveops_mar_is_acti_8ff225_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parkfeetier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("schedule", "tier_code"),
                name="diveops_unique_fee_tier_per_schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="parkzone",
            index=models.Index(
                fields=["marine_park", "zone_type"],
                name="diveops_par_marine__31b86c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="parkzone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("marine_park", "code"),
                name="diveops_unique_zone_code_per_park",
            ),
        ),
        migrations.AddIndex(
            model_name="parkrule",
            index=models.Index(
                fields=["marine_park", "effective_start"],
                name="diveops_par_marine__a3cf22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parkrule",
            index=models.Index(
                fields=["zone", "effective_start"],
                name="diveops_par_zone_id_8df2e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parkrule",
            index=models.Index(
                fields=["rule_type"], name="diveops_par_rule_ty_c8c140_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parkrule",
            index=models.Index(
                fields=["activity"], name="diveops_par_activit_ce3974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parkguidecredential",
            index=models.Index(
                fields=["marine_park", "is_active"],
                name="diveops_par_marine__9b91e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parkguidecredential",
            index=models.Index(fields=["diver"], name="diveops_par_diver_i_e8ff0f_idx"),
        ),
        migrations.AddIndex(
            model_name="parkguidecredential",
            index=models.Index(
                fields=["next_refresher_due_at"], name="diveops_par_next_re_13ee8d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parkguidecredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("marine_park", "diver"),
                name="diveops_unique_guide_credential_per_park",
            ),
        ),
        migrations.AddIndex(
            model_name="parkfeeschedule",
            index=models.Index(
                fields=["marine_park", "effective_start"],
                name="diveops_par_marine__89b223_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parkfeeschedule",
            index=models.Index(
                fields=["applies_to"], name="diveops_par_applies_001531_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselpermit",
            index=models.Index(
                fields=["marine_park", "is_active"],
                name="diveops_ves_marine__1fabca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vesselpermit",
            index=models.Index(
                fields=["operator"], name="diveops_ves_operato_242965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselpermit",
            index=models.Index(
                fields=["expires_at"], name="diveops_ves_expires_202225_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vesselpermit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("marine_park", "permit_number"),
                name="diveops_unique_permit_per_park",
            ),
        ),
    ]
