# Generated by Django 6.0 on 2026-01-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0031_refactor_protected_area"),
        ("django_agreements", "0001_initial"),
        ("django_catalog", "0002_add_catalogitemcomponent"),
        ("django_documents", "0001_initial"),
        ("django_geo", "0003_place_place_valid_latitude_and_more"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protectedareaguidecredential",
            options={"ordering": ["protected_area", "diver"]},
        ),
        migrations.AlterModelOptions(
            name="protectedareazone",
            options={"ordering": ["protected_area", "name"]},
        ),
        migrations.AlterModelOptions(
            name="vesselpermit",
            options={"ordering": ["protected_area", "vessel_name"]},
        ),
        migrations.RemoveIndex(
            model_name="divesite",
            name="diveops_div_marine__ff6d95_idx",
        ),
        migrations.RemoveIndex(
            model_name="protectedareafeeschedule",
            name="diveops_par_marine__89b223_idx",
        ),
        migrations.RemoveIndex(
            model_name="protectedareaguidecredential",
            name="diveops_par_marine__9b91e8_idx",
        ),
        migrations.RemoveIndex(
            model_name="protectedarearule",
            name="diveops_par_marine__a3cf22_idx",
        ),
        migrations.RemoveIndex(
            model_name="protectedareazone",
            name="diveops_par_marine__31b86c_idx",
        ),
        migrations.RemoveIndex(
            model_name="vesselpermit",
            name="diveops_ves_marine__1fabca_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedarea",
            new_name="diveops_pro_code_11ce41_idx",
            old_name="diveops_mar_code_d09bd9_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedarea",
            new_name="diveops_pro_is_acti_afcde1_idx",
            old_name="diveops_mar_is_acti_8ff225_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedarea",
            new_name="diveops_pro_parent__b30db6_idx",
            old_name="diveops_pro_parent__3b8e5a_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedareafeeschedule",
            new_name="diveops_pro_applies_861415_idx",
            old_name="diveops_par_applies_001531_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedareaguidecredential",
            new_name="diveops_pro_diver_i_71bcf8_idx",
            old_name="diveops_par_diver_i_e8ff0f_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedareaguidecredential",
            new_name="diveops_pro_next_re_f82d68_idx",
            old_name="diveops_par_next_re_13ee8d_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedarearule",
            new_name="diveops_pro_zone_id_7ad296_idx",
            old_name="diveops_par_zone_id_8df2e0_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedarearule",
            new_name="diveops_pro_rule_ty_024e01_idx",
            old_name="diveops_par_rule_ty_c8c140_idx",
        ),
        migrations.RenameIndex(
            model_name="protectedarearule",
            new_name="diveops_pro_activit_8379dc_idx",
            old_name="diveops_par_activit_ce3974_idx",
        ),
        migrations.AlterField(
            model_name="protectedarea",
            name="boundary_file",
            field=models.FileField(
                blank=True, null=True, upload_to="protected_areas/boundaries/%Y/"
            ),
        ),
        migrations.AlterField(
            model_name="protectedarea",
            name="designation_type",
            field=models.CharField(
                choices=[
                    ("national_park", "National Park"),
                    ("marine_park", "Marine Park"),
                    ("marine_reserve", "Marine Reserve"),
                    ("biosphere_reserve", "Biosphere Reserve"),
                    ("protected_area", "Protected Natural Area"),
                    ("sanctuary", "Marine Sanctuary"),
                ],
                default="protected_area",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="protectedarea",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="protected_areas",
                to="django_geo.place",
            ),
        ),
        migrations.AlterField(
            model_name="protectedareafeeschedule",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = applies area-wide",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_schedules",
                to="diveops.protectedareazone",
            ),
        ),
        migrations.AlterField(
            model_name="protectedarearule",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = applies area-wide",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="diveops.protectedareazone",
            ),
        ),
        migrations.AlterField(
            model_name="protectedareazone",
            name="boundary_file",
            field=models.FileField(
                blank=True, null=True, upload_to="protected_areas/zones/%Y/"
            ),
        ),
        migrations.AddIndex(
            model_name="divesite",
            index=models.Index(
                fields=["protected_area"], name="diveops_div_protect_a66886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="protectedareafeeschedule",
            index=models.Index(
                fields=["protected_area", "effective_start"],
                name="diveops_pro_protect_9cef23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="protectedareaguidecredential",
            index=models.Index(
                fields=["protected_area", "is_active"],
                name="diveops_pro_protect_6e2d8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="protectedarearule",
            index=models.Index(
                fields=["protected_area", "effective_start"],
                name="diveops_pro_protect_c0213b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="protectedareazone",
            index=models.Index(
                fields=["protected_area", "zone_type"],
                name="diveops_pro_protect_8fdfd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vesselpermit",
            index=models.Index(
                fields=["protected_area", "is_active"],
                name="diveops_ves_protect_22537a_idx",
            ),
        ),
    ]
