# Generated by Django 6.0 on 2026-01-06 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0032_alter_protectedareaguidecredential_options_and_more"),
        ("django_agreements", "0001_initial"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectedAreaPermit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permit_type",
                    models.CharField(
                        choices=[
                            ("guide", "Guide Credential"),
                            ("vessel", "Vessel Permit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permit_number",
                    models.CharField(
                        help_text="Unique permit/credential number within area and type",
                        max_length=50,
                    ),
                ),
                ("issued_at", models.DateField()),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vessel_name",
                    models.CharField(
                        blank=True,
                        help_text="Required for VESSEL permits",
                        max_length=100,
                    ),
                ),
                (
                    "vessel_registration",
                    models.CharField(
                        blank=True,
                        help_text="Vessel registration number (VESSEL permits)",
                        max_length=50,
                    ),
                ),
                (
                    "max_divers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max divers capacity (VESSEL permits)",
                        null=True,
                    ),
                ),
                (
                    "authorized_zones",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Zones this permit authorizes (empty = all zones)",
                        related_name="permits",
                        to="diveops.protectedareazone",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for GUIDE permits",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_permits",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operator organization (optional for VESSEL permits)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="area_permits",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "protected_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permits",
                        to="diveops.protectedarea",
                    ),
                ),
            ],
            options={
                "ordering": ["protected_area", "permit_type", "permit_number"],
            },
        ),
        migrations.CreateModel(
            name="GuidePermitDetails",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("carta_eval_signed_at", models.DateField(blank=True, null=True)),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False,
                        help_text="True if this guide is also the boat owner",
                    ),
                ),
                (
                    "last_refresher_at",
                    models.DateField(
                        blank=True,
                        help_text="Date of last park refresher course",
                        null=True,
                    ),
                ),
                (
                    "next_refresher_due_at",
                    models.DateField(
                        blank=True, help_text="When next refresher is due", null=True
                    ),
                ),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True)),
                (
                    "carta_eval_agreement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Signed carta evaluación document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guide_carta_evals_v2",
                        to="django_agreements.agreement",
                    ),
                ),
                (
                    "carta_eval_signed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Boat owner who signed (can be the guide themselves)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_carta_evals_v2",
                        to="django_parties.person",
                    ),
                ),
                (
                    "permit",
                    models.OneToOneField(
                        limit_choices_to={"permit_type": "guide"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_details",
                        to="diveops.protectedareapermit",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="protectedareapermit",
            index=models.Index(
                fields=["protected_area", "permit_type", "is_active"],
                name="diveops_pro_protect_215c62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="protectedareapermit",
            index=models.Index(fields=["diver"], name="diveops_pro_diver_i_42b204_idx"),
        ),
        migrations.AddIndex(
            model_name="protectedareapermit",
            index=models.Index(
                fields=["organization"], name="diveops_pro_organiz_463410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="protectedareapermit",
            index=models.Index(
                fields=["expires_at"], name="diveops_pro_expires_4c2b93_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("protected_area", "permit_type", "permit_number"),
                name="diveops_unique_permit_number_per_area_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("permit_type", "guide")
                ),
                fields=("protected_area", "diver"),
                name="diveops_unique_guide_permit_per_diver_area",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("permit_type", "guide"), _negated=True),
                    ("diver__isnull", False),
                    _connector="OR",
                ),
                name="diveops_guide_permit_requires_diver",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("permit_type", "guide"), _negated=True),
                    ("vessel_name", ""),
                    _connector="OR",
                ),
                name="diveops_guide_permit_no_vessel",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("permit_type", "vessel"), _negated=True),
                    models.Q(("vessel_name", ""), _negated=True),
                    _connector="OR",
                ),
                name="diveops_vessel_permit_requires_vessel",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("permit_type", "vessel"), _negated=True),
                    ("diver__isnull", True),
                    _connector="OR",
                ),
                name="diveops_vessel_permit_no_diver",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__isnull", True),
                    ("expires_at__gte", models.F("issued_at")),
                    _connector="OR",
                ),
                name="diveops_permit_expires_after_issued",
            ),
        ),
        migrations.AddIndex(
            model_name="guidepermitdetails",
            index=models.Index(
                fields=["next_refresher_due_at"], name="diveops_gui_next_re_1974d2_idx"
            ),
        ),
    ]
