# Generated by Django 6.0 on 2026-01-06 19:27
"""Data migration to copy ProtectedAreaGuideCredential and VesselPermit to ProtectedAreaPermit."""

from django.db import migrations


def migrate_guide_credentials(apps, schema_editor):
    """Migrate ProtectedAreaGuideCredential to ProtectedAreaPermit with type=GUIDE."""
    ProtectedAreaGuideCredential = apps.get_model("diveops", "ProtectedAreaGuideCredential")
    ProtectedAreaPermit = apps.get_model("diveops", "ProtectedAreaPermit")
    GuidePermitDetails = apps.get_model("diveops", "GuidePermitDetails")

    for old in ProtectedAreaGuideCredential.objects.all():
        # Create new permit
        permit = ProtectedAreaPermit.objects.create(
            id=old.id,  # Preserve UUID
            protected_area=old.protected_area,
            permit_type="guide",
            permit_number=old.credential_number or str(old.id)[:8],
            issued_at=old.issued_at,
            expires_at=old.expires_at,
            is_active=old.is_active,
            diver=old.diver,
            vessel_name="",
            created_at=old.created_at,
            updated_at=old.updated_at,
            deleted_at=old.deleted_at,
        )

        # Copy authorized zones
        permit.authorized_zones.set(old.authorized_zones.all())

        # Create guide details if there's extra data
        if any([
            old.carta_eval_agreement_id,
            old.carta_eval_signed_by_id,
            old.carta_eval_signed_at,
            old.is_owner,
            old.last_refresher_at,
            old.next_refresher_due_at,
            old.suspended_at,
            old.suspension_reason,
        ]):
            GuidePermitDetails.objects.create(
                permit=permit,
                carta_eval_agreement=old.carta_eval_agreement,
                carta_eval_signed_by=old.carta_eval_signed_by,
                carta_eval_signed_at=old.carta_eval_signed_at,
                is_owner=old.is_owner,
                last_refresher_at=old.last_refresher_at,
                next_refresher_due_at=old.next_refresher_due_at,
                suspended_at=old.suspended_at,
                suspension_reason=old.suspension_reason,
            )


def migrate_vessel_permits(apps, schema_editor):
    """Migrate VesselPermit to ProtectedAreaPermit with type=VESSEL."""
    VesselPermit = apps.get_model("diveops", "VesselPermit")
    ProtectedAreaPermit = apps.get_model("diveops", "ProtectedAreaPermit")

    for old in VesselPermit.objects.all():
        ProtectedAreaPermit.objects.create(
            protected_area=old.protected_area,
            permit_type="vessel",
            permit_number=old.permit_number,
            issued_at=old.issued_at,
            expires_at=old.expires_at,
            is_active=old.is_active,
            diver=None,
            vessel_name=old.vessel_name,
            vessel_registration=old.vessel_registration,
            organization=old.operator,
            max_divers=old.max_divers,
            created_at=old.created_at,
            updated_at=old.updated_at,
            deleted_at=old.deleted_at,
        )


def reverse_migration(apps, schema_editor):
    """Clear ProtectedAreaPermit data (reversible)."""
    ProtectedAreaPermit = apps.get_model("diveops", "ProtectedAreaPermit")
    GuidePermitDetails = apps.get_model("diveops", "GuidePermitDetails")
    GuidePermitDetails.objects.all().delete()
    ProtectedAreaPermit.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0033_unified_permits"),
    ]

    operations = [
        migrations.RunPython(migrate_guide_credentials, reverse_migration),
        migrations.RunPython(migrate_vessel_permits, reverse_migration),
    ]
