# Generated by Django 6.0 on 2026-01-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0034_migrate_permits_data"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="protectedareaguidecredential",
            name="diveops_pro_diver_i_71bcf8_idx",
        ),
        migrations.RemoveIndex(
            model_name="protectedareaguidecredential",
            name="diveops_pro_next_re_f82d68_idx",
        ),
        migrations.RemoveIndex(
            model_name="protectedareaguidecredential",
            name="diveops_pro_protect_6e2d8e_idx",
        ),
        migrations.RemoveConstraint(
            model_name="protectedareaguidecredential",
            name="diveops_unique_guide_credential_per_area",
        ),
        migrations.RemoveIndex(
            model_name="vesselpermit",
            name="diveops_ves_operato_242965_idx",
        ),
        migrations.RemoveIndex(
            model_name="vesselpermit",
            name="diveops_ves_expires_202225_idx",
        ),
        migrations.RemoveIndex(
            model_name="vesselpermit",
            name="diveops_ves_protect_22537a_idx",
        ),
        migrations.RemoveConstraint(
            model_name="vesselpermit",
            name="diveops_unique_permit_per_area",
        ),
        migrations.AlterField(
            model_name="protectedarearule",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("zone", "Zone"),
                    ("diver", "Individual Diver"),
                    ("group", "Dive Group"),
                    ("vessel", "Vessel"),
                    ("operator", "Operator/Shop"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="vesselpermit",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="vesselpermit",
            name="protected_area",
        ),
        migrations.DeleteModel(
            name="ProtectedAreaGuideCredential",
        ),
        migrations.DeleteModel(
            name="VesselPermit",
        ),
    ]
