# Generated by Django 6.0 on 2026-01-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0035_add_zone_to_rule_applies_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedarearule",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("diver", "Individual Diver"),
                    ("group", "Dive Group"),
                    ("vessel", "Vessel"),
                    ("operator", "Operator/Shop"),
                ],
                max_length=20,
            ),
        ),
    ]
