# Generated by Django 6.0 on 2026-01-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0036_remove_zone_from_applies_to"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedareapermit",
            name="diver",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for GUIDE/PHOTOGRAPHY permits, optional for DIVING",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_permits",
                to="diveops.diverprofile",
            ),
        ),
        migrations.AlterField(
            model_name="protectedareapermit",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional for VESSEL, required for DIVING if no diver",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="area_permits",
                to="django_parties.organization",
            ),
        ),
        migrations.AlterField(
            model_name="protectedareapermit",
            name="permit_type",
            field=models.CharField(
                choices=[
                    ("guide", "Guide Credential"),
                    ("vessel", "Vessel Permit"),
                    ("photography", "Photography Permit"),
                    ("diving", "Diving Permit"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="protectedareapermit",
            name="vessel_name",
            field=models.CharField(
                blank=True, help_text="Required for VESSEL permits only", max_length=100
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("permit_type", "photography"), _negated=True),
                    ("diver__isnull", False),
                    _connector="OR",
                ),
                name="diveops_photography_permit_requires_diver",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("permit_type", "photography"), _negated=True),
                    ("vessel_name", ""),
                    _connector="OR",
                ),
                name="diveops_photography_permit_no_vessel",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("permit_type", "diving"), _negated=True),
                    ("diver__isnull", False),
                    ("organization__isnull", False),
                    _connector="OR",
                ),
                name="diveops_diving_permit_requires_holder",
            ),
        ),
        migrations.AddConstraint(
            model_name="protectedareapermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("permit_type", "diving"), _negated=True),
                    ("vessel_name", ""),
                    _connector="OR",
                ),
                name="diveops_diving_permit_no_vessel",
            ),
        ),
    ]
