# Generated by Django 6.0 on 2026-01-06 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("diveops", "0037_add_photography_and_diving_permits"),
        ("django_agreements", "0001_initial"),
        ("django_documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedareapermit",
            name="permit_type",
            field=models.CharField(
                choices=[
                    ("guide", "Guide Credential"),
                    ("vessel", "Vessel Permit"),
                    ("photography", "Photography Permit"),
                    ("diving", "Ojo de Agua Permit"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SignableAgreement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template_version",
                    models.CharField(
                        help_text="Snapshot of template.version at creation time",
                        max_length=20,
                    ),
                ),
                ("party_a_object_id", models.CharField(max_length=255)),
                ("party_b_object_id", models.CharField(blank=True, max_length=255)),
                ("related_object_id", models.CharField(blank=True, max_length=255)),
                (
                    "content_snapshot",
                    models.TextField(
                        help_text="Rendered content at send time (editable until signed)"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 hash of content_snapshot", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("signed", "Signed"),
                            ("void", "Void"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        help_text="How agreement was delivered: email, link, in_person",
                        max_length=50,
                    ),
                ),
                (
                    "access_token_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash of access token (raw token never stored)",
                        max_length=64,
                    ),
                ),
                (
                    "token_consumed",
                    models.BooleanField(
                        default=False,
                        help_text="Token invalidated after signing (cannot be reused)",
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_by_name", models.CharField(blank=True, max_length=255)),
                ("signed_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("signed_user_agent", models.TextField(blank=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this agreement expires (enforced at signing)",
                        null=True,
                    ),
                ),
                (
                    "ledger_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signable_agreements",
                        to="django_agreements.agreement",
                    ),
                ),
                (
                    "party_a_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "party_b_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signature_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signature_for_agreements",
                        to="django_documents.document",
                    ),
                ),
                (
                    "signed_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_agreements",
                        to="django_documents.document",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signable_agreements",
                        to="diveops.agreementtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignableAgreementRevision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("revision_number", models.PositiveIntegerField()),
                ("previous_content_hash", models.CharField(max_length=64)),
                ("new_content_hash", models.CharField(max_length=64)),
                (
                    "change_note",
                    models.TextField(
                        help_text="Required explanation of why the change was made"
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="diveops.signableagreement",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["revision_number"],
            },
        ),
        migrations.AddIndex(
            model_name="signableagreement",
            index=models.Index(
                fields=["status", "created_at"], name="diveops_sig_status_e68138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signableagreement",
            index=models.Index(
                fields=["party_a_content_type", "party_a_object_id"],
                name="diveops_sig_party_a_169c68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signableagreement",
            index=models.Index(
                fields=["related_content_type", "related_object_id"],
                name="diveops_sig_related_9fe229_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signableagreement",
            index=models.Index(
                fields=["access_token_hash"], name="diveops_sig_access__865edd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signableagreement",
            index=models.Index(
                fields=["expires_at"], name="diveops_sig_expires_2a27f6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "signed"), _negated=True),
                    ("signed_at__isnull", False),
                    _connector="OR",
                ),
                name="signable_signed_requires_signed_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "sent"), _negated=True),
                    ("sent_at__isnull", False),
                    _connector="OR",
                ),
                name="signable_sent_requires_sent_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["sent", "signed"]), _negated=True),
                    models.Q(("access_token_hash", ""), _negated=True),
                    _connector="OR",
                ),
                name="signable_sent_signed_requires_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "signed"), _negated=True),
                    ("ledger_agreement__isnull", False),
                    _connector="OR",
                ),
                name="signable_signed_requires_ledger",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[a-f0-9]{64}$")),
                name="signable_valid_content_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["draft", "sent"])),
                fields=(
                    "template",
                    "party_a_content_type",
                    "party_a_object_id",
                    "related_content_type",
                    "related_object_id",
                ),
                name="signable_unique_pending_per_party_object",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreementrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("change_note", ""), _negated=True),
                name="revision_requires_change_note",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="signableagreementrevision",
            unique_together={("agreement", "revision_number")},
        ),
    ]
