# Generated by Django 6.0 on 2026-01-06 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("diveops", "0038_signable_agreement"),
        ("django_agreements", "0001_initial"),
        ("django_documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="signableagreement",
            name="signable_unique_pending_per_party_object",
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["draft", "sent"])),
                fields=(
                    "template",
                    "party_a_content_type",
                    "party_a_object_id",
                    "related_content_type",
                    "related_object_id",
                ),
                name="signable_unique_pending_per_party_object",
                nulls_distinct=False,
            ),
        ),
    ]
