# Generated by Django 6.0 on 2026-01-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0039_signable_agreement_nulls_not_distinct"),
    ]

    operations = [
        migrations.AddField(
            model_name="signableagreement",
            name="access_token",
            field=models.CharField(
                blank=True,
                help_text="Raw token for signing URL (displayed to staff)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="signableagreement",
            name="access_token_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of access token for verification",
                max_length=64,
            ),
        ),
    ]
