# Generated by Django 6.0 on 2026-01-07 00:00

from django.conf import settings
from django.db import migrations, models


def backfill_consent_for_signed_agreements(apps, schema_editor):
    """Set consent flags to True for all existing signed agreements.

    Since these were signed before consent tracking was added,
    we assume implicit consent was given at signing time.
    """
    SignableAgreement = apps.get_model("diveops", "SignableAgreement")
    SignableAgreement.objects.filter(status="signed").update(
        agreed_to_terms=True,
        agreed_to_esign=True,
    )


def reverse_backfill(apps, schema_editor):
    """Reverse: set consent flags back to False (no-op for data integrity)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("diveops", "0040_add_access_token_field"),
        ("django_agreements", "0001_initial"),
        ("django_documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add fields with default=False
        migrations.AddField(
            model_name="signableagreement",
            name="agreed_to_esign",
            field=models.BooleanField(
                default=False,
                help_text="Signer checked 'I consent to sign electronically'",
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="agreed_to_terms",
            field=models.BooleanField(
                default=False,
                help_text="Signer checked 'I agree to be bound by its terms'",
            ),
        ),
        # Step 2: Backfill existing signed agreements (assume implicit consent)
        migrations.RunPython(
            backfill_consent_for_signed_agreements,
            reverse_backfill,
        ),
        # Step 3: Add constraints (now safe because existing data is backfilled)
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "signed"), _negated=True),
                    ("agreed_to_terms", True),
                    _connector="OR",
                ),
                name="signable_signed_requires_terms_consent",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "signed"), _negated=True),
                    ("agreed_to_esign", True),
                    _connector="OR",
                ),
                name="signable_signed_requires_esign_consent",
            ),
        ),
    ]
