# Generated by Django 6.0 on 2026-01-07 00:05

from django.conf import settings
from django.db import migrations, models


def backfill_digital_proof_for_signed(apps, schema_editor):
    """Backfill placeholder values for signed agreements missing digital proof.

    These are test/legacy records - production would have real values.
    """
    SignableAgreement = apps.get_model("diveops", "SignableAgreement")
    SignableAgreement.objects.filter(
        status="signed",
        signed_ip__isnull=True,
    ).update(signed_ip="0.0.0.0")

    SignableAgreement.objects.filter(
        status="signed",
        signed_user_agent="",
    ).update(signed_user_agent="legacy/backfill")

    SignableAgreement.objects.filter(
        status="signed",
        signed_by_name="",
    ).update(signed_by_name="Unknown (legacy)")


def reverse_backfill(apps, schema_editor):
    """No-op reverse."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("diveops", "0041_add_consent_fields_to_signable_agreement"),
        ("django_agreements", "0001_initial"),
        ("django_documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Backfill any signed agreements missing digital proof data
        migrations.RunPython(backfill_digital_proof_for_signed, reverse_backfill),
        # Then add constraints
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "signed"), _negated=True),
                    ("signed_ip__isnull", False),
                    _connector="OR",
                ),
                name="signable_signed_requires_ip",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "signed"), _negated=True),
                    models.Q(("signed_user_agent", ""), _negated=True),
                    _connector="OR",
                ),
                name="signable_signed_requires_user_agent",
            ),
        ),
        migrations.AddConstraint(
            model_name="signableagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "signed"), _negated=True),
                    models.Q(("signed_by_name", ""), _negated=True),
                    _connector="OR",
                ),
                name="signable_signed_requires_signer_name",
            ),
        ),
    ]
