# Generated by Django 6.0 on 2026-01-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0042_add_digital_proof_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreementtemplate",
            name="target_party_type",
            field=models.CharField(
                choices=[
                    ("diver", "Diver"),
                    ("employee", "Employee"),
                    ("vendor", "Vendor"),
                    ("any", "Any Party"),
                ],
                default="diver",
                help_text="Type of party who should sign this template (diver, employee, vendor)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="agreementtemplate",
            index=models.Index(
                fields=["dive_shop", "target_party_type"],
                name="diveops_agr_dive_sh_target_idx",
            ),
        ),
    ]
