# Generated by Django 6.0 on 2026-01-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0043_add_target_party_type_to_agreement_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="signableagreementrevision",
            name="content_before",
            field=models.TextField(
                blank=True,
                help_text="Content snapshot before this revision (for diff viewing)",
            ),
        ),
    ]
