# Generated by Django 6.0 on 2026-01-07 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0044_add_content_before_to_revision"),
        ("django_documents", "0008_add_document_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLegalHold",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        help_text="Reason for the hold (e.g., 'Litigation: Smith v. DiveShop')",
                        max_length=200,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Case/ticket/reference number",
                        max_length=100,
                    ),
                ),
                (
                    "placed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the hold was placed"
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the hold was released (null = still active)",
                        null=True,
                    ),
                ),
                (
                    "release_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for releasing the hold",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this hold"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Legal Hold",
                "verbose_name_plural": "Document Legal Holds",
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRetentionPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        help_text="Document type this policy applies to (e.g., 'agreement', 'certification')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days to retain after creation (null = keep forever)",
                        null=True,
                    ),
                ),
                (
                    "trash_retention_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days to keep in Trash before auto-delete (default 30)",
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        help_text="Regulation/standard requiring this retention (e.g., 'IRS 7-year rule', 'PADI records')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of why this retention period is required",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this policy is currently enforced",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Retention Policy",
                "verbose_name_plural": "Document Retention Policies",
                "ordering": ["document_type"],
            },
        ),
        migrations.RenameIndex(
            model_name="agreementtemplate",
            new_name="diveops_agr_dive_sh_73fb30_idx",
            old_name="diveops_agr_dive_sh_target_idx",
        ),
        migrations.AddField(
            model_name="documentlegalhold",
            name="document",
            field=models.ForeignKey(
                help_text="Document under legal hold",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_holds",
                to="django_documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documentlegalhold",
            name="placed_by",
            field=models.ForeignKey(
                help_text="User who placed the hold",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_holds_placed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentlegalhold",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who released the hold",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_holds_released",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="documentlegalhold",
            index=models.Index(
                fields=["document", "released_at"],
                name="diveops_doc_documen_35345f_idx",
            ),
        ),
    ]
