# Generated by Django 6.0 on 2026-01-07 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0045_retention_policy_models"),
        ("django_documents", "0008_add_document_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "position_x",
                    models.FloatField(
                        blank=True,
                        help_text="X position as percentage (0-100) from left edge",
                        null=True,
                    ),
                ),
                (
                    "position_y",
                    models.FloatField(
                        blank=True,
                        help_text="Y position as percentage (0-100) from top edge",
                        null=True,
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        help_text="The diver tagged in this photo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_tags",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The photo document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_tags",
                        to="django_documents.document",
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this tag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_tags_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Tag",
                "verbose_name_plural": "Photo Tags",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document"], name="diveops_pho_documen_5d01b9_idx"
                    ),
                    models.Index(
                        fields=["diver"], name="diveops_pho_diver_i_246624_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "diver"),
                        name="phototag_unique_diver_per_photo",
                    )
                ],
            },
        ),
    ]
