# Generated by Django 6.0 on 2026-01-07 13:10

import django_singleton.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0046_add_photo_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openrouter_api_key",
                    models.CharField(
                        blank=True,
                        help_text="OpenRouter API key (falls back to OPENROUTER_API_KEY env var)",
                        max_length=255,
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI API key (falls back to OPENAI_API_KEY env var)",
                        max_length=255,
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        default="anthropic/claude-3-haiku",
                        help_text="Default AI model to use for processing",
                        max_length=100,
                    ),
                ),
                (
                    "ocr_enhancement_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable AI-powered OCR enhancement for scanned documents",
                    ),
                ),
                (
                    "auto_extract_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically extract text from uploaded documents",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
            bases=(django_singleton.mixins.EnvFallbackMixin, models.Model),
        ),
    ]
