# Generated by Django 6.0 on 2026-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0047_add_ai_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="signableagreement",
            name="signed_canvas_fingerprint",
            field=models.CharField(
                blank=True, help_text="SHA-256 of canvas fingerprint", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_device_memory",
            field=models.CharField(
                blank=True, help_text="Device memory in GB", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_geolocation",
            field=models.JSONField(
                blank=True, help_text="Lat/long if permitted", null=True
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_hardware_concurrency",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="CPU cores", null=True
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_language",
            field=models.CharField(
                blank=True, help_text="Browser language preference", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_platform",
            field=models.CharField(blank=True, help_text="OS/Platform", max_length=100),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_screen_resolution",
            field=models.CharField(
                blank=True, help_text="e.g., 1920x1080", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_timezone",
            field=models.CharField(
                blank=True, help_text="e.g., America/New_York", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_timezone_offset",
            field=models.SmallIntegerField(
                blank=True, help_text="UTC offset in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="signableagreement",
            name="signed_touch_support",
            field=models.BooleanField(
                blank=True, help_text="Touch screen device", null=True
            ),
        ),
    ]
