# Generated by Django 6.0 on 2026-01-08 01:52

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0048_add_fingerprint_fields"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalProviderProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("clinic", "Clinic"),
                            ("hospital", "Hospital"),
                            ("urgent_care", "Urgent Care"),
                            ("chamber", "Hyperbaric Chamber Facility"),
                            ("physician", "Individual Physician"),
                        ],
                        help_text="Type of medical provider",
                        max_length=20,
                    ),
                ),
                (
                    "has_hyperbaric_chamber",
                    models.BooleanField(
                        default=False,
                        help_text="Whether facility has a hyperbaric chamber",
                    ),
                ),
                (
                    "hyperbaric_details",
                    models.TextField(
                        blank=True,
                        help_text="Details about hyperbaric chamber (type, depth rating, etc.)",
                    ),
                ),
                (
                    "accepts_divers",
                    models.BooleanField(
                        default=True,
                        help_text="Whether provider accepts diving-related cases",
                    ),
                ),
                (
                    "accepts_emergencies",
                    models.BooleanField(
                        default=False,
                        help_text="Whether provider accepts emergency cases",
                    ),
                ),
                (
                    "is_dan_affiliated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether provider is affiliated with Divers Alert Network",
                    ),
                ),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Languages spoken by staff",
                    ),
                ),
                (
                    "certifications",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Relevant medical certifications (DAN, UHMS, etc.)",
                    ),
                ),
                (
                    "after_hours_phone",
                    models.CharField(
                        blank=True,
                        help_text="After-hours emergency contact number",
                        max_length=30,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions or notes about this provider",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for display (lower = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this provider is currently active",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        help_text="Base organization record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_provider_profile",
                        to="django_parties.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Provider Profile",
                "verbose_name_plural": "Medical Provider Profiles",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalProviderLocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Location name (e.g., 'Main Office', 'Chamber Facility')",
                        max_length=200,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(help_text="Street address line 1", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, help_text="Street address line 2", max_length=255
                    ),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State or province", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal/ZIP code", max_length=20
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Mexico", help_text="Country", max_length=100
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "hours_text",
                    models.CharField(
                        help_text="Hours of operation (e.g., 'Mon-Fri 9:00 AM - 5:00 PM')",
                        max_length=255,
                    ),
                ),
                (
                    "is_24_7",
                    models.BooleanField(
                        default=False, help_text="Whether location is open 24/7"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for this location",
                        max_length=30,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for this location",
                        max_length=254,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary/main location",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for display (lower = first)"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="Parent medical provider profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="diveops.medicalproviderprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Provider Location",
                "verbose_name_plural": "Medical Provider Locations",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalProviderRelationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary/preferred provider",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for display (lower = first)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this provider relationship (e.g., 'Preferred for complex cases')",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this relationship is currently active",
                    ),
                ),
                (
                    "dive_shop",
                    models.ForeignKey(
                        help_text="The dive shop/operator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_provider_relationships",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="The medical provider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dive_shop_relationships",
                        to="diveops.medicalproviderprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Provider Relationship",
                "verbose_name_plural": "Medical Provider Relationships",
                "ordering": ["sort_order", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("dive_shop", "provider"),
                        name="diveops_unique_shop_provider_relationship",
                    )
                ],
            },
        ),
    ]
