# Generated by Django 6.0 on 2026-01-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0049_medical_provider_models"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diverprofile",
            name="bcd_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="BCD/jacket size (XS, S, M, L, XL, XXL)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="diver_type",
            field=models.CharField(
                choices=[
                    ("identity", "Diver (Identity)"),
                    ("activity", "Does Diving (Activity)"),
                ],
                default="activity",
                help_text="Is diving their identity or just an activity they do?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="equipment_ownership",
            field=models.CharField(
                choices=[
                    ("none", "None - Rents All"),
                    ("partial", "Partial - Own Some Gear"),
                    ("full", "Full - Owns All Essential Gear"),
                ],
                default="none",
                help_text="Equipment ownership status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="fin_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fin size (e.g., S/M, M/L, or shoe size)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="gear_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional gear preferences or requirements",
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="glove_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Glove size (XS, S, M, L, XL)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="height_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Height in centimeters", null=True
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="mask_fit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mask fit notes (low volume, standard, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Weight in kilograms",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="weight_required_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Weight needed for neutral buoyancy in kg",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diverprofile",
            name="wetsuit_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Wetsuit size (XS, S, M, L, XL, XXL, or custom)",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="diverprofile",
            index=models.Index(
                fields=["equipment_ownership"], name="diveops_div_equipme_94159b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diverprofile",
            index=models.Index(
                fields=["diver_type"], name="diveops_div_diver_t_86bf0b_idx"
            ),
        ),
    ]
