# Generated by Django 6.0 on 2026-01-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0050_add_diver_gear_and_type_fields"),
        ("django_documents", "0009_media_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="diverprofile",
            name="profile_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile photo for this diver (selected from tagged photos)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diver_profile_photos",
                to="django_documents.document",
            ),
        ),
    ]
