# Generated by Django 6.0 on 2026-01-08 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0051_add_diver_profile_photo"),
        ("django_documents", "0009_media_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="diverprofile",
            name="photo_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Photo ID document uploaded during liability waiver signing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diver_photo_ids",
                to="django_documents.document",
            ),
        ),
    ]
