# Generated by Django 6.0 on 2026-01-08 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0052_add_photo_id_to_diver_profile"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiverRelationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse/Partner"),
                            ("buddy", "Dive Buddy"),
                            ("friend", "Friend"),
                            ("family", "Family Member"),
                            ("instructor_student", "Instructor/Student"),
                            ("travel_companion", "Travel Companion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_preferred_buddy",
                    models.BooleanField(
                        default=False, help_text="Prefer to pair these divers together"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "from_diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "to_diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="diveops.diverprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["from_diver", "relationship_type"],
                "indexes": [
                    models.Index(
                        fields=["from_diver", "to_diver"],
                        name="diveops_div_from_di_803195_idx",
                    ),
                    models.Index(
                        fields=["relationship_type"],
                        name="diveops_div_relatio_1173d5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("from_diver", "to_diver", "relationship_type"),
                        name="diveops_unique_diver_relationship",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_diver", models.F("to_diver")), _negated=True
                        ),
                        name="diveops_no_self_relationship",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse/Partner"),
                            ("parent", "Parent"),
                            ("child", "Child (Adult)"),
                            ("sibling", "Sibling"),
                            ("friend", "Friend"),
                            ("other_family", "Other Family Member"),
                            ("employer", "Employer"),
                            ("other", "Other"),
                        ],
                        help_text="Relationship to the diver",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Contact priority (1 = primary, 2 = secondary, etc.)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes (e.g., 'Also a diver - may be on same trip')",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        help_text="The person to contact in an emergency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emergency_contact_for",
                        to="django_parties.person",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contact_entries",
                        to="diveops.diverprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["diver", "priority"],
                "indexes": [
                    models.Index(
                        fields=["diver", "priority"],
                        name="diveops_eme_diver_i_722d91_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("diver", "priority"),
                        name="diveops_unique_emergency_contact_priority",
                    )
                ],
            },
        ),
    ]
