# Generated by Django 6.0 on 2026-01-08 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0053_add_emergency_contacts_and_diver_relationships"),
        ("django_documents", "0009_media_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="divesite",
            name="profile_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary profile photo for this dive site",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dive_site_profile_photos",
                to="django_documents.document",
            ),
        ),
        migrations.CreateModel(
            name="DiveSitePhoto",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order (lower = first). Featured photos use 1-4.",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured photos appear in the preview carousel (max 4)",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for this photo",
                        max_length=500,
                    ),
                ),
                (
                    "dive_site",
                    models.ForeignKey(
                        help_text="The dive site this photo belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_photos",
                        to="diveops.divesite",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The photo document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dive_site_photos",
                        to="django_documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_site_photos_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "position"],
                "indexes": [
                    models.Index(
                        fields=["dive_site", "is_featured", "position"],
                        name="diveops_div_dive_si_73150b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True), ("is_featured", True)
                        ),
                        fields=("dive_site", "position"),
                        name="diveops_site_photo_unique_featured_position",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("dive_site", "document"),
                        name="diveops_site_photo_unique_document",
                    ),
                ],
            },
        ),
    ]
