# Generated by Django 6.0 on 2026-01-08 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0054_add_dive_site_photos"),
        ("django_documents", "0009_media_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiveSitePhotoTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dive_site",
                    models.ForeignKey(
                        help_text="The dive site tagged in this photo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_tags",
                        to="diveops.divesite",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The photo document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dive_site_tags",
                        to="django_documents.document",
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this tag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dive_site_photo_tags_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dive Site Photo Tag",
                "verbose_name_plural": "Dive Site Photo Tags",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document"], name="diveops_div_documen_81373a_idx"
                    ),
                    models.Index(
                        fields=["dive_site"], name="diveops_div_dive_si_24358e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "dive_site"),
                        name="divesitephototag_unique_site_per_photo",
                    )
                ],
            },
        ),
    ]
