# Generated by Django 6.0 on 2026-01-08 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("diveops", "0055_add_dive_site_photo_tag"),
        ("django_documents", "0010_add_mediaasset_captured_at_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the target entity (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "link_source",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("derived_from_excursion", "From Excursion"),
                        ],
                        default="direct",
                        help_text="How this link was created (direct or derived from excursion)",
                        max_length=30,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Content type of the target entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this link",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        help_text="The media asset being linked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="django_documents.mediaasset",
                    ),
                ),
                (
                    "source_excursion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when link_source=derived_from_excursion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_media_links",
                        to="diveops.excursion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Link",
                "verbose_name_plural": "Media Links",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="diveops_med_content_f12c1a_idx",
                    ),
                    models.Index(
                        fields=["media_asset"], name="diveops_med_media_a_0766a8_idx"
                    ),
                    models.Index(
                        fields=["link_source"], name="diveops_med_link_so_165eb7_idx"
                    ),
                    models.Index(
                        fields=["source_excursion"],
                        name="diveops_med_source__8becdc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "media_asset",
                            "content_type",
                            "object_id",
                            "link_source",
                            "source_excursion",
                        ),
                        name="medialink_unique_per_source",
                    )
                ],
            },
        ),
    ]
