# Generated by Django 6.0 on 2026-01-08 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("diveops", "0056_add_medialink"),
        ("django_documents", "0010_add_mediaasset_captured_at_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="medialink",
            name="medialink_unique_per_source",
        ),
        migrations.AddConstraint(
            model_name="medialink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("link_source", "direct")),
                fields=("media_asset", "content_type", "object_id"),
                name="medialink_unique_direct",
            ),
        ),
        migrations.AddConstraint(
            model_name="medialink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("link_source", "derived_from_excursion")),
                fields=("media_asset", "content_type", "object_id", "source_excursion"),
                name="medialink_unique_derived",
            ),
        ),
    ]
