# Generated by Django 6.0 on 2026-01-08 14:33

from django.db import migrations


def migrate_photo_tags_to_medialink(apps, schema_editor):
    """Convert PhotoTag records to MediaLink.

    PhotoTag links Documents to DiverProfiles.
    MediaLink links MediaAssets to any entity via GenericFK.

    We need to find the MediaAsset for each PhotoTag's document,
    then create a MediaLink with link_source='direct'.
    """
    PhotoTag = apps.get_model('diveops', 'PhotoTag')
    MediaLink = apps.get_model('diveops', 'MediaLink')
    MediaAsset = apps.get_model('django_documents', 'MediaAsset')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    DiverProfile = apps.get_model('diveops', 'DiverProfile')

    # Get content type for DiverProfile
    diver_ct = ContentType.objects.get_for_model(DiverProfile)

    # Build a lookup of document_id -> media_asset for efficiency
    media_assets = {
        str(ma.document_id): ma
        for ma in MediaAsset.objects.all()
    }

    migrated_count = 0
    skipped_count = 0

    for tag in PhotoTag.objects.filter(deleted_at__isnull=True).select_related('document'):
        # Find MediaAsset for this document
        doc_id = str(tag.document_id)
        if doc_id not in media_assets:
            skipped_count += 1
            continue

        media_asset = media_assets[doc_id]

        # Create MediaLink (use get_or_create to handle duplicates)
        _, created = MediaLink.objects.get_or_create(
            media_asset=media_asset,
            content_type=diver_ct,
            object_id=str(tag.diver_id),
            link_source='direct',
            defaults={
                'linked_by': tag.tagged_by,
                'source_excursion': None,
            },
        )

        if created:
            migrated_count += 1

    print(f"PhotoTag migration: {migrated_count} migrated, {skipped_count} skipped (no MediaAsset)")


def migrate_dive_site_photo_tags_to_medialink(apps, schema_editor):
    """Convert DiveSitePhotoTag records to MediaLink.

    DiveSitePhotoTag links Documents to DiveSites.
    """
    DiveSitePhotoTag = apps.get_model('diveops', 'DiveSitePhotoTag')
    MediaLink = apps.get_model('diveops', 'MediaLink')
    MediaAsset = apps.get_model('django_documents', 'MediaAsset')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    DiveSite = apps.get_model('diveops', 'DiveSite')

    # Get content type for DiveSite
    site_ct = ContentType.objects.get_for_model(DiveSite)

    # Build a lookup of document_id -> media_asset for efficiency
    media_assets = {
        str(ma.document_id): ma
        for ma in MediaAsset.objects.all()
    }

    migrated_count = 0
    skipped_count = 0

    for tag in DiveSitePhotoTag.objects.filter(deleted_at__isnull=True).select_related('document'):
        # Find MediaAsset for this document
        doc_id = str(tag.document_id)
        if doc_id not in media_assets:
            skipped_count += 1
            continue

        media_asset = media_assets[doc_id]

        # Create MediaLink (use get_or_create to handle duplicates)
        _, created = MediaLink.objects.get_or_create(
            media_asset=media_asset,
            content_type=site_ct,
            object_id=str(tag.dive_site_id),
            link_source='direct',
            defaults={
                'linked_by': tag.tagged_by,
                'source_excursion': None,
            },
        )

        if created:
            migrated_count += 1

    print(f"DiveSitePhotoTag migration: {migrated_count} migrated, {skipped_count} skipped (no MediaAsset)")


def reverse_migration(apps, schema_editor):
    """Reverse migration - delete all direct MediaLinks.

    Note: This is destructive and will lose the migrated data.
    In practice, you probably don't want to reverse this migration.
    """
    MediaLink = apps.get_model('diveops', 'MediaLink')
    deleted_count, _ = MediaLink.objects.filter(link_source='direct').delete()
    print(f"Deleted {deleted_count} direct MediaLinks")


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0057_medialink_constraint_fix"),
        ("django_documents", "0010_add_mediaasset_captured_at_visibility"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(
            migrate_photo_tags_to_medialink,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            migrate_dive_site_photo_tags_to_medialink,
            reverse_code=reverse_migration,
        ),
    ]
