# Generated by Django 6.0 on 2026-01-08 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("diveops", "0058_migrate_photo_tags_to_medialink"),
        ("django_documents", "0010_add_mediaasset_captured_at_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="medialink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("link_source", "direct"),
                    models.Q(
                        ("link_source", "derived_from_excursion"),
                        ("source_excursion__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="medialink_derived_requires_source_excursion",
            ),
        ),
    ]
