# Generated by Django 6.0 on 2026-01-08 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0059_add_medialink_derived_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntitlementGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Entitlement code (e.g., 'content:owd-courseware')",
                        max_length=100,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice/Purchase"),
                            ("manual", "Manual Grant"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to source (invoice ID, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When entitlement becomes active (null = immediate)",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When entitlement expires (null = permanent)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlement_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "entitlement grant",
                "verbose_name_plural": "entitlement grants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code"], name="diveops_ent_user_id_c31068_idx"
                    ),
                    models.Index(
                        fields=["code", "ends_at"], name="diveops_ent_code_bf983b_idx"
                    ),
                ],
            },
        ),
    ]
