# Generated by Django 6.0 on 2026-01-08 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0060_add_entitlement_grant"),
        ("django_parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agreementtemplate",
            name="diveops_unique_published_template_per_type",
        ),
        migrations.AddField(
            model_name="agreementtemplate",
            name="diver_category",
            field=models.CharField(
                choices=[
                    ("all", "All Divers"),
                    ("certified", "Certified Divers Only"),
                    ("student", "Students in Training"),
                    ("dsd", "Discover Scuba (DSD/Try Dive)"),
                ],
                default="all",
                help_text="Which diver category needs this agreement (for waivers)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="agreementtemplate",
            index=models.Index(
                fields=["dive_shop", "diver_category"],
                name="diveops_agr_dive_sh_01f9ff_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "published"), ("deleted_at__isnull", True)
                ),
                fields=("dive_shop", "template_type", "diver_category"),
                name="diveops_unique_published_template_per_type_category",
            ),
        ),
    ]
