# Generated by Django 6.0 on 2026-01-09 01:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0061_add_diver_category_to_agreement_template"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenceDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key (e.g., 'diving.interests', 'food.dietary_restrictions')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Human-readable label", max_length=200),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Category for grouping (e.g., 'demographics', 'diving', 'food')",
                        max_length=50,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("str", "String"),
                            ("text", "Text"),
                            ("choice", "Single Choice"),
                            ("multi_choice", "Multiple Choice"),
                            ("date", "Date"),
                            ("json", "JSON"),
                        ],
                        help_text="Data type for the preference value",
                        max_length=20,
                    ),
                ),
                (
                    "choices_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Valid choices for choice/multi_choice types",
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("sensitive", "Sensitive"),
                        ],
                        default="internal",
                        help_text="Access control level",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this preference is currently in use",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
            ],
            options={
                "ordering": ["category", "sort_order", "key"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="diveops_pre_categor_fd9225_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartyPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "value_text",
                    models.TextField(
                        blank=True, help_text="Text/string value", null=True
                    ),
                ),
                (
                    "value_bool",
                    models.BooleanField(
                        blank=True, help_text="Boolean value", null=True
                    ),
                ),
                (
                    "value_int",
                    models.IntegerField(
                        blank=True, help_text="Integer value", null=True
                    ),
                ),
                (
                    "value_date",
                    models.DateField(blank=True, help_text="Date value", null=True),
                ),
                (
                    "value_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON value (for multi_choice, complex data)",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("survey", "Survey/Questionnaire"),
                            ("staff", "Staff Entry"),
                            ("import", "Data Import"),
                            ("self", "Self-Service Entry"),
                        ],
                        default="survey",
                        help_text="How this preference was collected",
                        max_length=20,
                    ),
                ),
                (
                    "source_instance_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Questionnaire instance ID if collected via survey",
                        max_length=255,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this preference was collected/updated",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="The person this preference belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="django_parties.person",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        help_text="The preference definition this value is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="diveops.preferencedefinition",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["person", "definition"],
                        name="diveops_par_person__db6bbc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "definition"), name="unique_person_preference"
                    )
                ],
            },
        ),
    ]
