# Generated by Django 6.0 on 2026-01-09 02:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0062_preferences_models"),
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name for the contact", max_length=200
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("bounced", "Bounced"),
                            ("opted_out", "Opted Out"),
                        ],
                        default="new",
                        help_text="Contact status in invite workflow",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Person who created this contact",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_contacts",
                        to="django_parties.person",
                    ),
                ),
                (
                    "linked_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked Person after they register",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_links",
                        to="django_parties.person",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="BuddyIdentity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.OneToOneField(
                        blank=True,
                        help_text="Reference to a registered Person",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_identity",
                        to="django_parties.person",
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        blank=True,
                        help_text="Reference to an unregistered Contact",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_identity",
                        to="diveops.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buddy Identity",
                "verbose_name_plural": "Buddy Identities",
            },
        ),
        migrations.CreateModel(
            name="DiveBuddy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse/Partner"),
                            ("friend", "Friend"),
                            ("dive_club", "Dive Club Member"),
                            ("instructor", "Instructor"),
                            ("family", "Family Member"),
                            ("coworker", "Coworker"),
                            ("other", "Other"),
                        ],
                        help_text="Type of relationship",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this buddy"),
                ),
                (
                    "buddy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The buddy (if they are a diver)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_of",
                        to="diveops.diverprofile",
                    ),
                ),
                (
                    "buddy_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="The buddy (if they are just a person, not a diver)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_person_for",
                        to="django_parties.person",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        help_text="The diver who owns this buddy relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dive_buddies",
                        to="diveops.diverprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dive Buddy",
                "verbose_name_plural": "Dive Buddies",
                "ordering": ["diver", "relationship"],
            },
        ),
        migrations.CreateModel(
            name="DiveTeam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team_type",
                    models.CharField(
                        choices=[("buddy", "Buddy Group")],
                        default="buddy",
                        help_text="Type of team",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for groups (blank for pairs)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this team is currently active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who created this team",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dive_teams",
                        to="django_parties.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiveTeamMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="Optional role in the team", max_length=50
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this team member"
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        help_text="The team member identity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="diveops.buddyidentity",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="The dive team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="diveops.diveteam",
                    ),
                ),
            ],
            options={
                "ordering": ["team", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["created_by"], name="diveops_con_created_e8f33b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["status"], name="diveops_con_status_79e2af_idx"),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__isnull", False), ("phone__isnull", False), _connector="OR"
                ),
                name="contact_requires_email_or_phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="buddyidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("contact__isnull", True), ("person__isnull", False)),
                    models.Q(("contact__isnull", False), ("person__isnull", True)),
                    _connector="OR",
                ),
                name="identity_exactly_one_of_person_or_contact",
            ),
        ),
        migrations.AddIndex(
            model_name="divebuddy",
            index=models.Index(fields=["diver"], name="diveops_div_diver_i_56860f_idx"),
        ),
        migrations.AddIndex(
            model_name="diveteam",
            index=models.Index(
                fields=["created_by"], name="diveops_div_created_81f524_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diveteam",
            index=models.Index(
                fields=["is_active"], name="diveops_div_is_acti_36c334_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diveteammember",
            index=models.Index(
                fields=["team", "identity"], name="diveops_div_team_id_5a45db_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diveteammember",
            constraint=models.UniqueConstraint(
                fields=("team", "identity"), name="unique_team_member"
            ),
        ),
    ]
