# Generated by Django 6.0 on 2026-01-09 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0063_buddy_system_models"),
        ("django_parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="excursion",
            name="is_override",
            field=models.BooleanField(
                default=False,
                help_text="True if this excursion was individually modified",
            ),
        ),
        migrations.AddField(
            model_name="excursion",
            name="occurrence_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Original occurrence datetime from RRULE (stable identity)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="excursion",
            name="override_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Which fields were overridden: {'capacity': true, 'price': true}",
            ),
        ),
        migrations.CreateModel(
            name="ExcursionSeries",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Series name (e.g., 'Saturday Morning 2-Tank')",
                        max_length=200,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=240,
                        help_text="Default excursion duration (4 hours default)",
                    ),
                ),
                (
                    "capacity_default",
                    models.PositiveIntegerField(
                        default=12, help_text="Default max divers per occurrence"
                    ),
                ),
                (
                    "price_default",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default price (null = use excursion_type base_price)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "meeting_place",
                    models.TextField(blank=True, help_text="Default meeting location"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this series"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "window_days",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Generate occurrences this many days ahead",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When occurrences were last synchronized",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excursion_series_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dive_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excursion_series",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "dive_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default dive site (can be overridden per occurrence)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="diveops.divesite",
                    ),
                ),
                (
                    "excursion_type",
                    models.ForeignKey(
                        help_text="Product type template for generated excursions",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="diveops.excursiontype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Excursion series",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="excursion",
            name="series",
            field=models.ForeignKey(
                blank=True,
                help_text="Series this excursion was generated from (null = standalone)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excursions",
                to="diveops.excursionseries",
            ),
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rrule_text",
                    models.CharField(
                        help_text="RFC 5545 RRULE string (e.g., 'FREQ=WEEKLY;BYDAY=SA;BYHOUR=8')",
                        max_length=500,
                    ),
                ),
                (
                    "dtstart",
                    models.DateTimeField(
                        help_text="Series start date/time (anchor for RRULE calculation)"
                    ),
                ),
                (
                    "dtend",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional series end date (no occurrences after this)",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Cancun",
                        help_text="IANA timezone for occurrence calculation",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description (e.g., 'Every Saturday at 8am')",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["dtstart"], name="diveops_rec_dtstart_d3161e_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="excursionseries",
            name="recurrence_rule",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excursion_series",
                to="diveops.recurrencerule",
            ),
        ),
        migrations.CreateModel(
            name="RecurrenceException",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "original_start",
                    models.DateTimeField(
                        help_text="The occurrence being modified (its original start time)"
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                            ("added", "Added (extra)"),
                        ],
                        help_text="Type of exception",
                        max_length=20,
                    ),
                ),
                (
                    "new_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="New start time (for rescheduled exceptions)",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for the exception (e.g., 'Weather conditions')",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="The recurrence rule this exception modifies",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="diveops.recurrencerule",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["rule", "original_start"],
                        name="diveops_rec_rule_id_4ee136_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("rule", "original_start"),
                        name="diveops_unique_recurrence_exception",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="excursionseries",
            index=models.Index(
                fields=["dive_shop", "status"], name="diveops_exc_dive_sh_a09a44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excursionseries",
            index=models.Index(fields=["status"], name="diveops_exc_status_314e97_idx"),
        ),
    ]
