# Generated by Django 6.0

from django.db import migrations


class Migration(migrations.Migration):
    """Add database trigger to prevent status changes on signed agreements.

    Business rule: Once an agreement is signed, it's legally binding and cannot
    be voided or have its status changed. If revocation is needed, a new
    revocation agreement must be created and signed instead.
    """

    dependencies = [
        ("diveops", "0064_recurring_excursions"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Create function to prevent status changes on signed agreements
            CREATE OR REPLACE FUNCTION prevent_signed_agreement_status_change()
            RETURNS TRIGGER AS $$
            BEGIN
                IF OLD.status = 'signed' AND NEW.status != 'signed' THEN
                    RAISE EXCEPTION 'Cannot change status of signed agreement. Signed agreements are legally binding records. To revoke, create and sign a new revocation agreement.'
                        USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Create trigger on signable agreement table
            DROP TRIGGER IF EXISTS tr_prevent_signed_agreement_status_change ON diveops_signableagreement;
            CREATE TRIGGER tr_prevent_signed_agreement_status_change
                BEFORE UPDATE OF status ON diveops_signableagreement
                FOR EACH ROW
                EXECUTE FUNCTION prevent_signed_agreement_status_change();
            """,
            reverse_sql="""
            -- Remove trigger and function
            DROP TRIGGER IF EXISTS tr_prevent_signed_agreement_status_change ON diveops_signableagreement;
            DROP FUNCTION IF EXISTS prevent_signed_agreement_status_change();
            """,
        ),
    ]
