# Generated by Django 6.0 on 2026-01-09 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0065_signed_agreement_immutable_trigger"),
        ("django_parties", "0002_add_diver_relationship_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiverRelationshipMeta",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Contact priority (1=primary, 2=secondary). Only for emergency_contact type.",
                        null=True,
                    ),
                ),
                (
                    "is_preferred_buddy",
                    models.BooleanField(
                        default=False,
                        help_text="Prefer to pair these divers together on excursions",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Dive-specific notes about this relationship",
                    ),
                ),
                (
                    "party_relationship",
                    models.OneToOneField(
                        help_text="The canonical PartyRelationship being extended",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diver_meta",
                        to="django_parties.partyrelationship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diver Relationship Metadata",
                "verbose_name_plural": "Diver Relationship Metadata",
                "indexes": [
                    models.Index(
                        fields=["priority"], name="diveops_div_priorit_b07c02_idx"
                    ),
                    models.Index(
                        fields=["is_preferred_buddy"],
                        name="diveops_div_is_pref_310578_idx",
                    ),
                ],
            },
        ),
    ]
