# Generated by Django 6.0 on 2026-01-09 17:50
"""
Data migration: Copy EmergencyContact and DiverRelationship to PartyRelationship.

This is Phase 2 of the relationship consolidation (ADR-001).
Creates PartyRelationship + DiverRelationshipMeta records for each existing
EmergencyContact and DiverRelationship record.

Original records are NOT deleted - they remain for backward compatibility
until Phase 5 (cleanup) when they will be deprecated and eventually removed.
"""

from django.db import migrations


# Mapping from EmergencyContact.relationship to PartyRelationship.relationship_type
EMERGENCY_CONTACT_TYPE_MAP = {
    "spouse": "emergency_contact",  # Store as emergency_contact, spouse relationship noted in meta
    "parent": "emergency_contact",
    "child": "emergency_contact",
    "sibling": "emergency_contact",
    "friend": "emergency_contact",
    "other_family": "emergency_contact",
    "employer": "emergency_contact",
    "other": "emergency_contact",
}

# Mapping from DiverRelationship.relationship_type to PartyRelationship.relationship_type
DIVER_RELATIONSHIP_TYPE_MAP = {
    "spouse": "spouse",
    "buddy": "buddy",
    "friend": "friend",
    "family": "relative",
    "instructor_student": "instructor",  # Asymmetric - from instructor perspective
    "travel_companion": "travel_companion",
}


def migrate_emergency_contacts_forward(apps, schema_editor):
    """Copy EmergencyContact records to PartyRelationship + DiverRelationshipMeta."""
    EmergencyContact = apps.get_model("diveops", "EmergencyContact")
    PartyRelationship = apps.get_model("django_parties", "PartyRelationship")
    DiverRelationshipMeta = apps.get_model("diveops", "DiverRelationshipMeta")

    created_count = 0
    skipped_count = 0

    for ec in EmergencyContact.objects.filter(deleted_at__isnull=True):
        # Check if a PartyRelationship already exists for this pair
        existing = PartyRelationship.objects.filter(
            from_person=ec.diver.person,
            to_person=ec.contact_person,
            relationship_type="emergency_contact",
            deleted_at__isnull=True,
        ).first()

        if existing:
            # Already migrated or created directly - update meta if needed
            if not hasattr(existing, "diver_meta") or not DiverRelationshipMeta.objects.filter(
                party_relationship=existing
            ).exists():
                DiverRelationshipMeta.objects.create(
                    party_relationship=existing,
                    priority=ec.priority,
                    notes=f"Migrated from EmergencyContact. Original relationship: {ec.relationship}. {ec.notes}".strip(),
                )
                created_count += 1
            else:
                skipped_count += 1
            continue

        # Create PartyRelationship
        pr = PartyRelationship.objects.create(
            from_person=ec.diver.person,
            to_person=ec.contact_person,
            relationship_type="emergency_contact",
            title=ec.get_relationship_display() if hasattr(ec, "get_relationship_display") else ec.relationship,
            is_active=True,
            is_primary=(ec.priority == 1),
        )

        # Create DiverRelationshipMeta extension
        DiverRelationshipMeta.objects.create(
            party_relationship=pr,
            priority=ec.priority,
            notes=f"Migrated from EmergencyContact. Original relationship: {ec.relationship}. {ec.notes}".strip(),
        )
        created_count += 1

    print(f"  Migrated {created_count} emergency contacts, skipped {skipped_count} duplicates")


def migrate_diver_relationships_forward(apps, schema_editor):
    """Copy DiverRelationship records to PartyRelationship + DiverRelationshipMeta."""
    DiverRelationship = apps.get_model("diveops", "DiverRelationship")
    PartyRelationship = apps.get_model("django_parties", "PartyRelationship")
    DiverRelationshipMeta = apps.get_model("diveops", "DiverRelationshipMeta")

    created_count = 0
    skipped_count = 0

    for dr in DiverRelationship.objects.filter(deleted_at__isnull=True):
        # Map old relationship type to new
        new_type = DIVER_RELATIONSHIP_TYPE_MAP.get(dr.relationship_type, "buddy")

        # Check if a PartyRelationship already exists for this pair + type
        existing = PartyRelationship.objects.filter(
            from_person=dr.from_diver.person,
            to_person=dr.to_diver.person,
            relationship_type=new_type,
            deleted_at__isnull=True,
        ).first()

        if existing:
            # Already migrated - update meta if needed
            if not DiverRelationshipMeta.objects.filter(party_relationship=existing).exists():
                DiverRelationshipMeta.objects.create(
                    party_relationship=existing,
                    is_preferred_buddy=dr.is_preferred_buddy,
                    notes=f"Migrated from DiverRelationship. {dr.notes}".strip(),
                )
                created_count += 1
            else:
                skipped_count += 1
            continue

        # Create PartyRelationship
        pr = PartyRelationship.objects.create(
            from_person=dr.from_diver.person,
            to_person=dr.to_diver.person,
            relationship_type=new_type,
            is_active=True,
            is_primary=dr.is_preferred_buddy,
        )

        # Create DiverRelationshipMeta extension
        DiverRelationshipMeta.objects.create(
            party_relationship=pr,
            is_preferred_buddy=dr.is_preferred_buddy,
            notes=f"Migrated from DiverRelationship. {dr.notes}".strip(),
        )
        created_count += 1

    print(f"  Migrated {created_count} diver relationships, skipped {skipped_count} duplicates")


def validate_migration(apps, schema_editor):
    """Validate that all records were migrated correctly."""
    EmergencyContact = apps.get_model("diveops", "EmergencyContact")
    DiverRelationship = apps.get_model("diveops", "DiverRelationship")
    PartyRelationship = apps.get_model("django_parties", "PartyRelationship")
    DiverRelationshipMeta = apps.get_model("diveops", "DiverRelationshipMeta")

    ec_count = EmergencyContact.objects.filter(deleted_at__isnull=True).count()
    dr_count = DiverRelationship.objects.filter(deleted_at__isnull=True).count()
    pr_count = PartyRelationship.objects.filter(
        deleted_at__isnull=True,
        relationship_type__in=["emergency_contact", "spouse", "buddy", "friend", "relative", "travel_companion", "instructor"],
    ).count()
    meta_count = DiverRelationshipMeta.objects.filter(deleted_at__isnull=True).count()

    print(f"  Validation: {ec_count} EmergencyContacts, {dr_count} DiverRelationships")
    print(f"  Created: {pr_count} PartyRelationships, {meta_count} DiverRelationshipMeta records")

    # Note: Counts may not match exactly due to:
    # - Existing PartyRelationship records that weren't migrated
    # - Bidirectional DiverRelationships creating 2 PR records


def noop(apps, schema_editor):
    """No-op for reverse migration - data stays in place."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0066_add_diver_relationship_meta"),
        ("django_parties", "0002_add_diver_relationship_meta"),
    ]

    operations = [
        migrations.RunPython(
            migrate_emergency_contacts_forward,
            reverse_code=noop,
        ),
        migrations.RunPython(
            migrate_diver_relationships_forward,
            reverse_code=noop,
        ),
        migrations.RunPython(
            validate_migration,
            reverse_code=noop,
        ),
    ]
