# Generated by Django 6.0 on 2026-01-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0067_migrate_relationships_to_party_relationship"),
        ("django_agreements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch to enable/disable email sending",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("console", "Console (Development)"),
                            ("ses_api", "Amazon SES API"),
                            ("ses_smtp", "Amazon SES SMTP"),
                        ],
                        default="console",
                        help_text="Email provider to use",
                        max_length=20,
                    ),
                ),
                (
                    "sandbox_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Safety toggle - when enabled, emails are logged but not sent",
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        help_text="Default sender email address (must be verified in SES)",
                        max_length=254,
                    ),
                ),
                (
                    "default_from_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for sender (e.g., 'Dive Shop Name')",
                        max_length=100,
                    ),
                ),
                (
                    "reply_to_email",
                    models.EmailField(
                        blank=True,
                        help_text="Default reply-to address (optional)",
                        max_length=254,
                    ),
                ),
                (
                    "aws_region",
                    models.CharField(
                        default="us-east-1",
                        help_text="AWS region for SES (e.g., us-east-1, eu-west-1)",
                        max_length=50,
                    ),
                ),
                (
                    "configuration_set",
                    models.CharField(
                        blank=True,
                        help_text="SES Configuration Set name for tracking (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "aws_access_key_id",
                    models.CharField(
                        blank=True,
                        help_text="AWS Access Key ID for SES",
                        max_length=255,
                    ),
                ),
                (
                    "aws_secret_access_key",
                    models.CharField(
                        blank=True,
                        help_text="AWS Secret Access Key for SES",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        help_text="SMTP host (for SMTP provider)",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(
                        default=587, help_text="SMTP port (typically 587 for TLS)"
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True, help_text="SMTP username", max_length=255
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True, help_text="SMTP password", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Settings",
                "verbose_name_plural": "Email Settings",
            },
        ),
        migrations.RemoveIndex(
            model_name="diverequipmentrental",
            name="diveops_div_booking_1347f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="diverequipmentrental",
            name="diveops_div_rented__7693ca_idx",
        ),
        migrations.RemoveConstraint(
            model_name="diverequipmentrental",
            name="diveops_rental_quantity_positive",
        ),
        migrations.RemoveConstraint(
            model_name="diverequipmentrental",
            name="diveops_rental_cost_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="diverequipmentrental",
            name="diveops_rental_charge_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="diverequipmentrental",
            name="diveops_rental_unique_per_booking",
        ),
        migrations.RemoveIndex(
            model_name="entitlementgrant",
            name="diveops_ent_user_id_c31068_idx",
        ),
        migrations.RemoveIndex(
            model_name="entitlementgrant",
            name="diveops_ent_code_bf983b_idx",
        ),
        migrations.RemoveIndex(
            model_name="partypreference",
            name="diveops_par_person__db6bbc_idx",
        ),
        migrations.RemoveConstraint(
            model_name="partypreference",
            name="unique_person_preference",
        ),
        migrations.RemoveIndex(
            model_name="preferencedefinition",
            name="diveops_pre_categor_fd9225_idx",
        ),
        migrations.AlterField(
            model_name="guidepermitdetails",
            name="carta_eval_agreement",
            field=models.ForeignKey(
                blank=True,
                help_text="Signed carta evaluacion document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guide_carta_evals_v2",
                to="django_agreements.agreement",
            ),
        ),
        migrations.RemoveField(
            model_name="entitlementgrant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="partypreference",
            name="definition",
        ),
        migrations.RemoveField(
            model_name="partypreference",
            name="person",
        ),
        migrations.DeleteModel(
            name="DiverEquipmentRental",
        ),
        migrations.DeleteModel(
            name="EntitlementGrant",
        ),
        migrations.DeleteModel(
            name="PreferenceDefinition",
        ),
        migrations.DeleteModel(
            name="PartyPreference",
        ),
    ]
