# Generated by Django 6.0 on 2026-01-11 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0069_add_email_template"),
        ("django_communication", "0007_group_conversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiveBuddyGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        help_text="The underlying group conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_group",
                        to="django_communication.conversation",
                    ),
                ),
                (
                    "dive_team",
                    models.OneToOneField(
                        help_text="The dive team this chat belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_chat",
                        to="diveops.diveteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dive Buddy Group",
                "verbose_name_plural": "Dive Buddy Groups",
                "ordering": ["-created_at"],
            },
        ),
    ]
