# Generated by Django 6.0 on 2026-01-11 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0070_divebuddygroup"),
        ("django_communication", "0008_flow_types"),
        ("django_parties", "0004_add_lead_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Medical Onboarding', 'New Diver Setup')",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("onboarding", "New Diver Onboarding"),
                            ("medical", "Medical Clearance"),
                            ("liability", "Liability Waiver"),
                            ("booking", "Booking Confirmation"),
                            ("certification", "Certification Process"),
                            ("custom", "Custom Flow"),
                        ],
                        default="custom",
                        help_text="Category of flow",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this flow accomplishes",
                    ),
                ),
                (
                    "auto_create_conversation",
                    models.BooleanField(
                        default=True,
                        help_text="Create conversation automatically when flow starts",
                    ),
                ),
                (
                    "conversation_subject_template",
                    models.CharField(
                        default="{flow_name} - {customer_name}",
                        help_text="Template for conversation subject. Variables: {flow_name}, {customer_name}",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this flow type is currently active",
                    ),
                ),
                (
                    "agreement_templates",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Agreement templates required for this flow",
                        related_name="flow_types",
                        to="diveops.agreementtemplate",
                    ),
                ),
                (
                    "dive_shop",
                    models.ForeignKey(
                        help_text="Dive shop that owns this flow type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_types",
                        to="django_parties.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow Type",
                "verbose_name_plural": "Flow Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FlowThread",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        help_text="Current status of this flow",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this flow was started"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this flow was completed", null=True
                    ),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        help_text="The conversation for this flow",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_thread",
                        to="django_communication.conversation",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer going through this flow",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_threads",
                        to="django_parties.person",
                    ),
                ),
                (
                    "triggered_by_agreement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agreement that triggered this flow (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flow_threads",
                        to="diveops.signableagreement",
                    ),
                ),
                (
                    "flow_type",
                    models.ForeignKey(
                        help_text="The type of flow this thread represents",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threads",
                        to="diveops.flowtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow Thread",
                "verbose_name_plural": "Flow Threads",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="flowtype",
            index=models.Index(
                fields=["dive_shop", "is_active"], name="diveops_flo_dive_sh_a222a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowtype",
            index=models.Index(
                fields=["category"], name="diveops_flo_categor_b31784_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="flowtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("dive_shop", "name"),
                name="unique_active_flow_type_per_shop",
            ),
        ),
        migrations.AddIndex(
            model_name="flowthread",
            index=models.Index(
                fields=["customer", "status"], name="diveops_flo_custome_4e2a9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowthread",
            index=models.Index(
                fields=["flow_type", "status"], name="diveops_flo_flow_ty_e275c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowthread",
            index=models.Index(
                fields=["status", "started_at"], name="diveops_flo_status_c60ecc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="flowthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active"), ("deleted_at__isnull", True)),
                fields=("flow_type", "customer"),
                name="unique_active_flow_per_customer",
            ),
        ),
    ]
