# Generated by Django 6.0 on 2026-01-11 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0071_flow_types"),
        ("django_documents", "0010_add_mediaasset_captured_at_visibility"),
        ("django_encounters", "0001_initial"),
        ("django_parties", "0004_add_lead_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dive",
            index=models.Index(
                fields=["dive_site"], name="diveops_div_dive_si_12a4bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="divercertification",
            index=models.Index(
                fields=["diver", "expires_on"], name="diveops_div_diver_i_5174a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="divercertification",
            index=models.Index(
                fields=["is_verified"], name="diveops_div_is_veri_452b2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diverprofile",
            index=models.Index(
                fields=["medical_clearance_valid_until"],
                name="diveops_div_medical_b50d9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="diverprofile",
            index=models.Index(
                fields=["waiver_signed_at"], name="diveops_div_waiver__19889a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diverrelationship",
            index=models.Index(
                fields=["is_preferred_buddy"], name="diveops_div_is_pref_3142fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excursion",
            index=models.Index(
                fields=["excursion_type"], name="diveops_exc_excursi_d5a39f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excursion",
            index=models.Index(
                fields=["series"], name="diveops_exc_series__11d4c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excursionroster",
            index=models.Index(fields=["diver"], name="diveops_exc_diver_i_509a7a_idx"),
        ),
        migrations.AddIndex(
            model_name="excursionroster",
            index=models.Index(
                fields=["dive_completed"], name="diveops_exc_dive_co_58df24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excursionroster",
            index=models.Index(
                fields=["checked_in_at"], name="diveops_exc_checked_a7c89f_idx"
            ),
        ),
    ]
