# Generated by Django 6.0 on 2026-01-01 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("poi", "Point of Interest"),
                            ("landmark", "Landmark"),
                            ("facility", "Facility"),
                            ("intersection", "Intersection"),
                            ("other", "Other"),
                        ],
                        default="poi",
                        max_length=20,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="MX", max_length=2)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery Zone"),
                            ("coverage", "Coverage Area"),
                            ("tax_jurisdiction", "Tax Jurisdiction"),
                            ("other", "Other"),
                        ],
                        default="delivery",
                        max_length=20,
                    ),
                ),
                (
                    "center_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "center_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("radius_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
