# Generated by Django 6.0 on 2026-01-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
