# Generated by Django 6.0 on 2026-01-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_geo", "0002_place_deleted_at_servicearea_deleted_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="place_valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="place_valid_longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicearea",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("center_latitude__gte", -90), ("center_latitude__lte", 90)
                ),
                name="servicearea_valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicearea",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("center_longitude__gte", -180), ("center_longitude__lte", 180)
                ),
                name="servicearea_valid_longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicearea",
            constraint=models.CheckConstraint(
                condition=models.Q(("radius_km__gt", 0)),
                name="servicearea_positive_radius",
            ),
        ),
    ]
