# Generated by Django 5.2.9 on 2025-12-31 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this module (e.g., 'pharmacy', 'billing')",
                        max_length=100,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this module provides",
                        verbose_name="description",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Global default: if True, module is enabled unless org overrides",
                        verbose_name="active",
                    ),
                ),
            ],
            options={
                "verbose_name": "module",
                "verbose_name_plural": "modules",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="OrgModuleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enabled",
                    models.BooleanField(
                        help_text="Override: True to enable, False to disable for this org",
                        verbose_name="enabled",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_states",
                        to="django_modules.module",
                        verbose_name="module",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_states",
                        to="testapp.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization module state",
                "verbose_name_plural": "organization module states",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "module"), name="unique_org_module_state"
                    )
                ],
            },
        ),
    ]
