# Generated by Django 6.0 on 2026-01-03 03:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("context_object_id", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "effective_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the session started in business terms",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the system learned about this session",
                    ),
                ),
                (
                    "context_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "stopped_at"],
                        name="django_work_user_id_effafd_idx",
                    ),
                    models.Index(
                        fields=["context_content_type", "context_object_id"],
                        name="django_work_context_1a19e5_idx",
                    ),
                    models.Index(
                        fields=["effective_at"], name="django_work_effecti_fb2b9f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("stopped_at__isnull", True), ("deleted_at__isnull", True)
                        ),
                        fields=("user",),
                        name="unique_active_session_per_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("duration_seconds__isnull", True),
                                ("stopped_at__isnull", True),
                            ),
                            models.Q(
                                ("duration_seconds__isnull", False),
                                ("stopped_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="worksession_duration_consistency",
                    ),
                ],
            },
        ),
    ]
