# Generated by Django 6.0 on 2026-01-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_worklog", "0002_add_worksession_time_semantics"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="worksession",
            new_name="django_work_effecti_fb2b9f_idx",
            old_name="django_work_effecti_3f4e5a_idx",
        ),
        migrations.AddField(
            model_name="worksession",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
