# Generated by Django 6.0 on 2026-01-03 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "django_worklog",
            "0003_rename_django_work_effecti_3f4e5a_idx_django_work_effecti_fb2b9f_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="worksession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("stopped_at__isnull", True), ("deleted_at__isnull", True)
                ),
                fields=("user",),
                name="unique_active_session_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="worksession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("duration_seconds__isnull", True), ("stopped_at__isnull", True)
                    ),
                    models.Q(
                        ("duration_seconds__isnull", False),
                        ("stopped_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="worksession_duration_consistency",
            ),
        ),
    ]
