# Generated by Django 6.0 on 2026-01-07 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("validity_days", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            models.Q(("status", "archived"), _negated=True),
                        ),
                        fields=("slug",),
                        name="unique_active_definition_slug",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField()),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Yes/No"),
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("choice", "Single Choice"),
                            ("multi_choice", "Multiple Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                ("help_text", models.TextField(blank=True, default="")),
                ("is_required", models.BooleanField(default=True)),
                ("triggers_flag", models.BooleanField(default=False)),
                ("choices", models.JSONField(blank=True, default=list)),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="django_questionnaires.questionnairedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireInstance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("definition_version", models.CharField(max_length=20)),
                ("respondent_object_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("flagged", "Flagged"),
                            ("cleared", "Cleared"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("flagged_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("clearance_notes", models.TextField(blank=True, default="")),
                (
                    "clearance_document_object_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "clearance_document_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clearance_documents",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleared_questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="django_questionnaires.questionnairedefinition",
                    ),
                ),
                (
                    "respondent_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_instances",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("answer_text", models.TextField(blank=True, null=True)),
                ("answer_bool", models.BooleanField(blank=True, null=True)),
                ("answer_date", models.DateField(blank=True, null=True)),
                (
                    "answer_number",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("answer_choices", models.JSONField(blank=True, null=True)),
                ("triggered_flag", models.BooleanField(default=False)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="django_questionnaires.questionnaireinstance",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="django_questionnaires.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question__sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("definition", "sequence"),
                name="unique_question_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="questionnaireinstance",
            index=models.Index(
                fields=["respondent_content_type", "respondent_object_id"],
                name="django_ques_respond_cd4376_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionnaireinstance",
            index=models.Index(fields=["status"], name="django_ques_status_914408_idx"),
        ),
        migrations.AddIndex(
            model_name="questionnaireinstance",
            index=models.Index(
                fields=["expires_at"], name="django_ques_expires_02e3ec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("instance", "question"),
                name="unique_response_per_question",
            ),
        ),
    ]
