# Generated by Django 6.0 on 2026-01-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_questionnaires", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireinstance",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
