# Generated by Django 6.0 on 2026-01-08 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_questionnaires", "0002_add_instance_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireinstance",
            name="void_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="questionnaireinstance",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnaireinstance",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_questionnaires",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("flagged", "Flagged"),
                    ("cleared", "Cleared"),
                    ("expired", "Expired"),
                    ("voided", "Voided"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
