# Generated by Django 6.0 on 2026-01-07 13:04

import django_singleton.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("secret_key", models.CharField(blank=True, max_length=255)),
                ("base_url", models.CharField(blank=True, default="", max_length=255)),
            ],
            bases=(django_singleton.mixins.EnvFallbackMixin, models.Model),
        ),
    ]
