# Generated by Django 6.0 on 2026-01-03 15:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_agreements", "0001_initial"),
        ("django_catalog", "0001_initial"),
        ("django_encounters", "0001_initial"),
        ("django_ledger", "0001_initial"),
        ("django_parties", "0001_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Human-readable invoice number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("voided", "Voided"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="ISO currency code for all line items",
                        max_length=3,
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Sum of line item totals before tax",
                        max_digits=19,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Total tax amount",
                        max_digits=19,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Final total (subtotal + tax)",
                        max_digits=19,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agreement used for pricing (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="django_agreements.agreement",
                    ),
                ),
                (
                    "basket",
                    models.OneToOneField(
                        help_text="The committed basket this invoice was generated from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="django_catalog.basket",
                    ),
                ),
                (
                    "billed_to",
                    models.ForeignKey(
                        help_text="The patient/party being billed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices_received",
                        to="django_parties.person",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        help_text="The encounter this invoice relates to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="django_encounters.encounter",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="The organization issuing the invoice",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices_issued",
                        to="django_parties.organization",
                    ),
                ),
                (
                    "ledger_transaction",
                    models.OneToOneField(
                        blank=True,
                        help_text="The double-entry transaction recording this invoice",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="django_ledger.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Display name at time of invoicing", max_length=255
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price_amount",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "line_total_amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="quantity * unit_price (calculated at creation)",
                        max_digits=19,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Tax rate as decimal (0.08 = 8%)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "price_scope_type",
                    models.CharField(
                        help_text="The scope type that determined the price (global/organization/party/agreement)",
                        max_length=20,
                    ),
                ),
                (
                    "price_rule_id",
                    models.UUIDField(help_text="The Price record ID that was applied"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "priced_basket_item",
                    models.OneToOneField(
                        help_text="The priced basket item this line was generated from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_line",
                        to="pricing.pricedbasketitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal_amount__gte", 0)),
                name="invoice_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="invoice_total_non_negative",
            ),
        ),
    ]
