# Generated by Django 6.0 on 2026-01-02 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_id",
                    models.CharField(
                        help_text="ID of the target object (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded file", upload_to="documents/%Y/%m/%d/"
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="MIME content type (e.g., application/pdf)",
                        max_length=100,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Document classification (e.g., invoice_pdf, receipt_image)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the document",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 checksum for integrity verification",
                        max_length=64,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (page count, author, etc.)",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days to retain document (None = forever)",
                        null=True,
                    ),
                ),
                (
                    "retention_policy",
                    models.CharField(
                        default="standard",
                        help_text="Retention policy classification (standard, regulatory, legal, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Explicit expiration date (None = never expires)",
                        null=True,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        help_text="Content type of the target object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_id"],
                        name="django_docu_target__39a446_idx",
                    ),
                    models.Index(
                        fields=["document_type"], name="django_docu_documen_43439c_idx"
                    ),
                    models.Index(
                        fields=["checksum"], name="django_docu_checksu_9e13ed_idx"
                    ),
                ],
            },
        ),
    ]
