# Generated by Django 6.0 on 2026-01-07 02:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "storage_backend",
                    models.CharField(default="filesystem", max_length=50),
                ),
                (
                    "blob_path",
                    models.CharField(
                        db_index=True,
                        help_text="Relative path under MEDIA_ROOT",
                        max_length=1000,
                    ),
                ),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("size_bytes", models.BigIntegerField()),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="django_documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Current version of this document (new uploads use DocumentVersion)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="django_documents.documentversion",
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["document", "created_at"], name="django_docu_documen_93b411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["sha256"], name="django_docu_sha256_882aed_idx"),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["blob_path"], name="django_docu_blob_pa_e7a1f6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("storage_backend", "sha256", "blob_path"),
                name="uniq_blob_identity",
            ),
        ),
    ]
