# Generated by Django 6.0 on 2026-01-07 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_documents", "0002_documentversion_document_current_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("path", models.CharField(db_index=True, max_length=1000)),
                ("depth", models.PositiveIntegerField(default=0)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "owner_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="django_documents.documentfolder",
                    ),
                ),
            ],
            options={
                "ordering": ["path", "name"],
                "indexes": [
                    models.Index(fields=["path"], name="django_docu_path_75315f_idx"),
                    models.Index(
                        fields=["parent", "name"], name="django_docu_parent__9e9294_idx"
                    ),
                    models.Index(
                        fields=["owner_content_type", "owner_id"],
                        name="django_docu_owner_c_d2829b_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("depth", 0), ("parent__isnull", True)),
                            models.Q(("depth__gt", 0), ("parent__isnull", False)),
                            _connector="OR",
                        ),
                        name="folder_depth_consistency",
                    )
                ],
                "unique_together": {("parent", "slug")},
            },
        ),
    ]
