# Generated by Django 6.0 on 2026-01-07 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_documents", "0003_documentfolder"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolderPermission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("grantee_id", models.CharField(max_length=255)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "View"),
                            (20, "Download"),
                            (30, "Upload"),
                            (40, "Edit"),
                            (50, "Manage"),
                        ],
                        default=10,
                    ),
                ),
                (
                    "inherited",
                    models.BooleanField(
                        default=True, help_text="If True, applies to all subfolders"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="django_documents.documentfolder",
                    ),
                ),
                (
                    "grantee_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["folder", "level"],
                        name="django_docu_folder__49c4bb_idx",
                    ),
                    models.Index(
                        fields=["grantee_content_type", "grantee_id"],
                        name="django_docu_grantee_040341_idx",
                    ),
                ],
                "unique_together": {("folder", "grantee_content_type", "grantee_id")},
            },
        ),
    ]
