# Generated by Django 6.0 on 2026-01-07 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_documents", "0004_folderpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_filename", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Viewed metadata"),
                            ("download", "Downloaded file"),
                            ("preview", "Previewed file"),
                            ("upload", "Uploaded file"),
                            ("edit", "Edited metadata"),
                            ("move", "Moved to folder"),
                            ("delete", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("accessed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="django_documents.document",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="django_documents.documentversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "accessed_at"],
                        name="django_docu_documen_a2271f_idx",
                    ),
                    models.Index(
                        fields=["actor", "accessed_at"],
                        name="django_docu_actor_i_edecdd_idx",
                    ),
                    models.Index(
                        fields=["action", "accessed_at"],
                        name="django_docu_action_908b2c_idx",
                    ),
                ],
            },
        ),
    ]
