# Generated by Django 6.0 on 2026-01-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_documents", "0005_documentaccesslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                default="document",
                help_text="Document/media category for filtering",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Folder containing this document (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="django_documents.documentfolder",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Content type of the target object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="target_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of the target object (CharField for UUID support)",
                max_length=255,
            ),
        ),
    ]
