# Generated by Django 6.0 on 2026-01-07 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_documents", "0007_populate_document_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="Status of text extraction",
                        max_length=20,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full text extracted from the document",
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Method used for extraction (pdf_text, ocr, direct_read, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of pages processed (for PDFs)",
                        null=True,
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approximate word count of extracted text",
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Detected language code (e.g., 'en', 'es')",
                        max_length=10,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When extraction was completed", null=True
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken to extract content in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if extraction failed",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated summary of the document",
                    ),
                ),
                (
                    "entities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extracted entities (names, dates, amounts, etc.)",
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AI model used for processing (e.g., 'claude-3-haiku')",
                        max_length=100,
                    ),
                ),
                (
                    "ai_processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When AI processing was completed",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        help_text="The document this content was extracted from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="django_documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Content",
                "verbose_name_plural": "Document Contents",
                "indexes": [
                    models.Index(
                        fields=["status"], name="django_docu_status_27f4df_idx"
                    ),
                    models.Index(
                        fields=["extraction_method"],
                        name="django_docu_extract_49c785_idx",
                    ),
                ],
            },
        ),
    ]
