# Generated by Django 6.0 on 2026-01-08 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_documents", "0008_add_document_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        help_text="Type of media (image or video)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Processing status",
                        max_length=20,
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Height in pixels", null=True
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Duration in seconds (video only)",
                        null=True,
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the photo/video was taken (from EXIF)",
                        null=True,
                    ),
                ),
                (
                    "camera_make",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Camera manufacturer (from EXIF)",
                        max_length=100,
                    ),
                ),
                (
                    "camera_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Camera model (from EXIF)",
                        max_length=100,
                    ),
                ),
                (
                    "gps_latitude",
                    models.FloatField(
                        blank=True, help_text="GPS latitude (from EXIF)", null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.FloatField(
                        blank=True, help_text="GPS longitude (from EXIF)", null=True
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alt text for accessibility",
                        max_length=500,
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        help_text="The document containing the media file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_asset",
                        to="django_documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Asset",
                "verbose_name_plural": "Media Assets",
            },
        ),
        migrations.CreateModel(
            name="MediaRendition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("thumb", "Thumbnail (150px)"),
                            ("small", "Small (320px)"),
                            ("medium", "Medium (640px)"),
                            ("large", "Large (1280px)"),
                            ("poster", "Video Poster"),
                        ],
                        help_text="Role/size of this rendition",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The generated rendition file",
                        upload_to="documents/renditions/%Y/%m/%d/",
                    ),
                ),
                ("width", models.PositiveIntegerField(help_text="Width in pixels")),
                ("height", models.PositiveIntegerField(help_text="Height in pixels")),
                (
                    "file_size",
                    models.PositiveBigIntegerField(help_text="File size in bytes"),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Output format (jpeg, webp, png)",
                        max_length=10,
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        help_text="The media asset this rendition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renditions",
                        to="django_documents.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Rendition",
                "verbose_name_plural": "Media Renditions",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the target entity", max_length=255
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("gallery", "Gallery"),
                            ("avatar", "Avatar"),
                            ("cover", "Cover Image"),
                            ("hero", "Hero Image"),
                            ("certificate", "Certificate"),
                            ("evidence", "Evidence"),
                            ("marketing", "Marketing"),
                        ],
                        help_text="Purpose of this attachment",
                        max_length=20,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for galleries"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary attachment for this purpose",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Caption for the attachment",
                        max_length=500,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alt text for accessibility",
                        max_length=500,
                    ),
                ),
                (
                    "attached_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this attachment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Content type of the target entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document being attached",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="django_documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["purpose", "sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="django_docu_content_c25afa_idx",
                    ),
                    models.Index(
                        fields=["purpose", "sort_order"],
                        name="django_docu_purpose_14168b_idx",
                    ),
                ],
                "unique_together": {
                    ("document", "content_type", "object_id", "purpose")
                },
            },
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["kind"], name="django_docu_kind_5cf47f_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["status"], name="django_docu_status_2743a2_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["taken_at"], name="django_docu_taken_a_80fd4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediarendition",
            index=models.Index(
                fields=["media_asset", "role"], name="django_docu_media_a_985027_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediarendition",
            unique_together={("media_asset", "role")},
        ),
    ]
