# Generated by Django 6.0 on 2026-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_documents", "0009_media_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="captured_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="User-settable capture date (vs EXIF taken_at)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("internal", "Internal"),
                    ("public", "Public"),
                ],
                db_index=True,
                default="private",
                help_text="Visibility level for this media",
                max_length=20,
            ),
        ),
    ]
