# Generated by Django 6.0 on 2026-01-03 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(help_text="Tag display name", max_length=50)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly tag identifier", unique=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#808080",
                        help_text="Hex color code (e.g., #FF0000)",
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the tag",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_id",
                    models.CharField(
                        help_text="ID of the target object (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                ("content", models.TextField(help_text="Note content")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("private", "Private"),
                        ],
                        default="internal",
                        help_text="Note visibility level",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        help_text="Content type of the target object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_id"],
                        name="django_note_target__2ddc14_idx",
                    ),
                    models.Index(
                        fields=["visibility"], name="django_note_visibil_727425_idx"
                    ),
                    models.Index(
                        fields=["author"], name="django_note_author__c12af4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ObjectTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_id",
                    models.CharField(
                        help_text="ID of the target object (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who applied the tag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        help_text="Content type of the target object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The tag applied to the object",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_tags",
                        to="django_notes.tag",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_id"],
                        name="django_note_target__046d94_idx",
                    ),
                    models.Index(fields=["tag"], name="django_note_tag_id_9918e5_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_content_type", "target_id", "tag"),
                        name="objecttag_unique_per_target",
                    )
                ],
            },
        ),
    ]
