# Generated by Django 6.0 on 2026-01-03 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objecttag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="objecttag",
            constraint=models.UniqueConstraint(
                fields=("target_content_type", "target_id", "tag"),
                name="objecttag_unique_per_target",
            ),
        ),
    ]
