# Generated by Django 5.2.9 on 2025-12-30 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_display",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of actor identity (email, name, etc.) for safety",
                        max_length=200,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action type: create, update, delete, view, login, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "model_label",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Model label in app.model format (e.g., "emr.Encounter")',
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="Primary key of affected object (UUID or integer as string)",
                        max_length=50,
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of object at time of action",
                        max_length=200,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Before/after field changes: {"field": {"old": x, "new": y}}',
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Client user agent string", max_length=500
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        help_text="Request ID for correlation",
                        max_length=100,
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True, help_text="Distributed trace ID", max_length=100
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (reason, ticket, etc.)",
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        help_text="Data sensitivity classification",
                        max_length=20,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="True if action was performed by system (not a user)",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="django_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor_user", "created_at"],
                        name="django_audi_actor_u_0f72b0_idx",
                    ),
                    models.Index(
                        fields=["model_label", "created_at"],
                        name="django_audi_model_l_da9fa9_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="django_audi_action_3e4906_idx",
                    ),
                    models.Index(
                        fields=["object_id", "model_label"],
                        name="django_audi_object__b0d80b_idx",
                    ),
                ],
            },
        ),
    ]
