# Generated by Django 6.0 on 2026-01-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_audit_log", "0002_add_auditlog_effective_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="django_audi_effecti_f9611a_idx",
            old_name="django_audi_effecti_9f8e7d_idx",
        ),
    ]
