# Generated by Django 6.0 on 2026-01-07 01:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_provider_configs",
                    models.TextField(
                        db_column="provider_configs",
                        default="{}",
                        help_text="Provider-specific configs as JSON",
                    ),
                ),
                (
                    "default_provider",
                    models.CharField(default="openrouter", max_length=50),
                ),
                (
                    "default_model",
                    models.CharField(
                        default="anthropic/claude-sonnet-4", max_length=100
                    ),
                ),
                ("default_max_tokens", models.PositiveIntegerField(default=4096)),
                (
                    "default_temperature",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.7"), max_digits=3
                    ),
                ),
                (
                    "pin_model_version",
                    models.BooleanField(
                        default=False,
                        help_text="If True, append version date to model name for reproducibility",
                    ),
                ),
                (
                    "pinned_model_versions",
                    models.JSONField(default=dict, help_text="Model → version mapping"),
                ),
                ("fallback_provider", models.CharField(blank=True, max_length=50)),
                ("fallback_model", models.CharField(blank=True, max_length=100)),
                (
                    "daily_cost_limit_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max spend per day (null = unlimited)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "per_request_cost_limit_usd",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.50"),
                        help_text="Pre-flight cost check rejects requests above this",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_cost_limit_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pause_on_budget_exceeded", models.BooleanField(default=False)),
                (
                    "token_budgets",
                    models.JSONField(
                        default=dict,
                        help_text="Operation-specific max_tokens: {operation: max_tokens}",
                    ),
                ),
                (
                    "model_pricing",
                    models.JSONField(
                        default=dict,
                        help_text="Pricing per model: {model: {input_per_1m: X, output_per_1m: Y}}",
                    ),
                ),
                (
                    "requests_per_minute_anonymous",
                    models.PositiveIntegerField(default=10),
                ),
                (
                    "requests_per_minute_authenticated",
                    models.PositiveIntegerField(default=60),
                ),
                (
                    "requests_per_day_per_user",
                    models.PositiveIntegerField(default=1000),
                ),
                ("request_cooldown_seconds", models.PositiveIntegerField(default=2)),
                (
                    "provider_health",
                    models.JSONField(
                        default=dict,
                        help_text="Health state: {provider: {failures: N, last_failure: ts, circuit_open: bool}}",
                    ),
                ),
                (
                    "circuit_breaker_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Consecutive failures before opening circuit",
                    ),
                ),
                (
                    "circuit_breaker_reset_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutes before attempting to close circuit",
                    ),
                ),
                ("max_retries", models.PositiveIntegerField(default=3)),
                (
                    "retry_base_delay_seconds",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.0"), max_digits=5
                    ),
                ),
                (
                    "retry_max_delay_seconds",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.0"), max_digits=5
                    ),
                ),
                (
                    "retry_jitter",
                    models.BooleanField(
                        default=True,
                        help_text="Add randomness to retry delays to prevent thundering herd",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("debug_mode", models.BooleanField(default=False)),
                (
                    "log_prompt_hash",
                    models.BooleanField(
                        default=True, help_text="Always safe: SHA-256 for deduplication"
                    ),
                ),
                (
                    "log_prompts",
                    models.BooleanField(
                        default=False,
                        help_text="Privacy concern: stores prompt preview",
                    ),
                ),
                (
                    "log_responses",
                    models.BooleanField(
                        default=False,
                        help_text="Storage concern: stores response preview",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Service Configuration",
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("target_object_id", models.CharField(blank=True, max_length=255)),
                (
                    "operation",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., chat, analyze, classify, tagging",
                        max_length=100,
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Pre-request estimate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "actual_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Post-request actual",
                        max_digits=10,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("used_fallback", models.BooleanField(default=False)),
                (
                    "prompt_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("prompt_preview", models.CharField(blank=True, max_length=500)),
                ("response_preview", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_object_id", models.CharField(max_length=255)),
                ("analysis_type", models.CharField(db_index=True, max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("input_data", models.JSONField(default=dict)),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("result", models.JSONField(default=dict)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("validation_passed", models.BooleanField(default=True)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("repair_attempts", models.PositiveIntegerField(default=0)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usage_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="django_ai_services.aiusagelog",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["user", "created_at"], name="django_ai_s_user_id_eaad2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["operation", "created_at"],
                name="django_ai_s_operati_95c456_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["provider", "model", "created_at"],
                name="django_ai_s_provide_831770_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="django_ai_s_target__5b465c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["success", "created_at"], name="django_ai_s_success_aae952_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["session_id", "created_at"],
                name="django_ai_s_session_8724ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="django_ai_s_target__959e41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(
                fields=["analysis_type", "created_at"],
                name="django_ai_s_analysi_fc4877_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(
                fields=["input_hash"], name="django_ai_s_input_h_160c30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(
                fields=["triggered_by", "created_at"],
                name="django_ai_s_trigger_4118f7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aianalysis",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                    _connector="OR",
                ),
                name="ai_analysis_confidence_range",
            ),
        ),
    ]
