# Generated by Django 6.0 on 2026-01-06 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogItemComponent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of this component per parent item",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display/processing order within the assembly",
                        verbose_name="sequence",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False,
                        help_text="If True, component can be excluded when ordering the parent",
                        verbose_name="is optional",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Optional notes about this component relationship",
                        max_length=200,
                        verbose_name="notes",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        help_text="The catalog item included in the assembly",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_assemblies",
                        to="django_catalog.catalogitem",
                        verbose_name="component item",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="The assembly/bundle that contains this component",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="django_catalog.catalogitem",
                        verbose_name="parent item",
                    ),
                ),
            ],
            options={
                "verbose_name": "catalog item component",
                "verbose_name_plural": "catalog item components",
                "ordering": ["parent", "sequence", "component__display_name"],
                "indexes": [
                    models.Index(
                        fields=["parent", "sequence"],
                        name="django_cata_parent__c6ebe2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("parent", "component"),
                        name="unique_component_per_parent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="component_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("parent", models.F("component")), _negated=True
                        ),
                        name="component_no_self_reference",
                    ),
                ],
            },
        ),
    ]
