# Generated by Django 5.2.9 on 2025-12-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="USD",
                        help_text="ISO 4217 currency code for pricing",
                        max_length=3,
                        verbose_name="default currency",
                    ),
                ),
                (
                    "allow_inactive_items",
                    models.BooleanField(
                        default=False,
                        help_text="If True, inactive catalog items can be added to baskets",
                        verbose_name="allow inactive items",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional JSON metadata for custom configuration",
                        verbose_name="metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "catalog settings",
                "verbose_name_plural": "catalog settings",
            },
        ),
    ]
