# Generated by Django 6.0 on 2026-01-03 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_catalog",
            "0005_rename_django_cata_effecti_1a2b3c_idx_django_cata_effecti_d18588_idx_and_more",
        ),
        ("testapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="basket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft"), ("deleted_at__isnull", True)),
                fields=("encounter",),
                name="unique_active_basket_per_encounter",
            ),
        ),
    ]
