# Generated by Django 6.0 on 2026-01-03 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_catalog", "0006_basket_unique_active_basket_per_encounter"),
        ("testapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="basketitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="basketitem_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispenselog",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="dispenselog_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="workitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 0), ("priority__lte", 100)),
                name="workitem_priority_range",
            ),
        ),
    ]
