# Generated by Django 6.0 on 2026-01-03 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("clinic", "Clinic"),
                            ("hospital", "Hospital"),
                            ("supplier", "Supplier/Distributor"),
                            ("school", "School/Institution"),
                            ("nonprofit", "Non-profit"),
                            ("government", "Government Agency"),
                            ("partner", "Business Partner"),
                            ("other", "Other"),
                        ],
                        default="company",
                        max_length=20,
                        verbose_name="organization type",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax identification number (EIN, RFC, VAT, etc.)",
                        max_length=30,
                        verbose_name="tax ID",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="legal name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="middle name"
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        help_text="What this person prefers to be called",
                        max_length=150,
                        verbose_name="preferred name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from name or manually set",
                        max_length=300,
                        verbose_name="display name",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of death"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "phone_is_mobile",
                    models.BooleanField(default=True, verbose_name="is mobile"),
                ),
                (
                    "phone_has_whatsapp",
                    models.BooleanField(default=False, verbose_name="has WhatsApp"),
                ),
                (
                    "phone_can_receive_sms",
                    models.BooleanField(default=True, verbose_name="can receive SMS"),
                ),
                (
                    "address_is_home",
                    models.BooleanField(default=True, verbose_name="home address"),
                ),
                (
                    "address_is_billing",
                    models.BooleanField(default=False, verbose_name="billing address"),
                ),
                (
                    "address_is_shipping",
                    models.BooleanField(default=False, verbose_name="shipping address"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("household", "Household"),
                            ("family", "Family"),
                            ("partnership", "Partnership"),
                            ("team", "Team"),
                            ("department", "Department"),
                            ("other", "Other"),
                        ],
                        default="household",
                        max_length=20,
                        verbose_name="group type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "primary_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_for_groups",
                        to="django_parties.person",
                        verbose_name="primary contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Demographics",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-binary"),
                            ("prefer_not_say", "Prefer not to say"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                            ("domestic_partner", "Domestic Partnership"),
                            ("prefer_not_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="marital status",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nationality"
                    ),
                ),
                (
                    "country_of_birth",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country of birth"
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ethnicity"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        help_text="ISO 639-1 code (e.g., en, es, fr)",
                        max_length=10,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "additional_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ISO 639-1 codes",
                        verbose_name="additional languages",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="education level"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="occupation"
                    ),
                ),
                (
                    "household_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of people in household",
                        null=True,
                        verbose_name="household size",
                    ),
                ),
                (
                    "has_children",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="has children"
                    ),
                ),
                (
                    "number_of_children",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="number of children"
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics",
                        to="django_parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "demographics",
                "verbose_name_plural": "demographics",
            },
        ),
        migrations.CreateModel(
            name="PartyURL",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "url_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp Business"),
                            ("google_maps", "Google Maps"),
                            ("yelp", "Yelp"),
                            ("github", "GitHub"),
                            ("portfolio", "Portfolio"),
                            ("blog", "Blog"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=20,
                        verbose_name="URL type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary"),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Social media handle without @ symbol",
                        max_length=100,
                        verbose_name="username/handle",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Custom label like "Personal Blog" or "Company LinkedIn"',
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verified ownership of this URL",
                        verbose_name="verified",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Show on public profiles",
                        verbose_name="public",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="django_parties.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="django_parties.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="django_parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
                "ordering": ["-is_primary", "url_type", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("person__isnull", False),
                                ("organization__isnull", True),
                                ("group__isnull", True),
                            ),
                            models.Q(
                                ("person__isnull", True),
                                ("organization__isnull", False),
                                ("group__isnull", True),
                            ),
                            models.Q(
                                ("person__isnull", True),
                                ("organization__isnull", True),
                                ("group__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="partyurl_exactly_one_party",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartyRelationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("contractor_individual", "Individual Contractor"),
                            ("contact", "Contact"),
                            ("owner", "Owner/Executive"),
                            ("customer", "Customer"),
                            ("contractor_org", "Contractor Organization"),
                            ("vendor", "Vendor/Supplier"),
                            ("partner", "Business Partner"),
                            ("client", "Client"),
                            ("subsidiary", "Subsidiary"),
                            ("parent_company", "Parent Company"),
                            ("member", "Member"),
                            ("head", "Head of Household"),
                            ("spouse", "Spouse/Partner"),
                            ("dependent", "Dependent"),
                            ("emergency_contact", "Emergency Contact"),
                            ("guardian", "Guardian"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("manager", "Manager"),
                            ("reports_to", "Reports To"),
                        ],
                        max_length=30,
                        verbose_name="relationship type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Job title or role description",
                        max_length=100,
                        verbose_name="title",
                    ),
                ),
                (
                    "contract_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="contract start"
                    ),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="contract end"
                    ),
                ),
                (
                    "contract_signed",
                    models.BooleanField(default=False, verbose_name="contract signed"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary relationship of this type",
                        verbose_name="primary",
                    ),
                ),
                (
                    "from_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="django_parties.organization",
                        verbose_name="from organization",
                    ),
                ),
                (
                    "to_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="django_parties.group",
                        verbose_name="to group",
                    ),
                ),
                (
                    "to_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="django_parties.organization",
                        verbose_name="to organization",
                    ),
                ),
                (
                    "from_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="django_parties.person",
                        verbose_name="from person",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="django_parties.person",
                        verbose_name="to person",
                    ),
                ),
            ],
            options={
                "verbose_name": "party relationship",
                "verbose_name_plural": "party relationships",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("from_person__isnull", False),
                                ("from_organization__isnull", True),
                            ),
                            models.Q(
                                ("from_person__isnull", True),
                                ("from_organization__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="partyrelationship_exactly_one_from",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("to_person__isnull", False),
                                ("to_organization__isnull", True),
                                ("to_group__isnull", True),
                            ),
                            models.Q(
                                ("to_person__isnull", True),
                                ("to_organization__isnull", False),
                                ("to_group__isnull", True),
                            ),
                            models.Q(
                                ("to_person__isnull", True),
                                ("to_organization__isnull", True),
                                ("to_group__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="partyrelationship_exactly_one_to",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("work", "Work"),
                            ("billing", "Billing"),
                            ("support", "Support"),
                            ("newsletter", "Newsletter"),
                            ("info", "Info"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="email type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=100, verbose_name="label"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "receives_marketing",
                    models.BooleanField(
                        default=False, verbose_name="receives marketing"
                    ),
                ),
                (
                    "receives_transactional",
                    models.BooleanField(
                        default=True, verbose_name="receives transactional"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="django_parties.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="django_parties.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="django_parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "email address",
                "verbose_name_plural": "email addresses",
                "ordering": ["-is_primary", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("person__isnull", False),
                                ("organization__isnull", True),
                                ("group__isnull", True),
                            ),
                            models.Q(
                                ("person__isnull", True),
                                ("organization__isnull", False),
                                ("group__isnull", True),
                            ),
                            models.Q(
                                ("person__isnull", True),
                                ("organization__isnull", True),
                                ("group__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="email_exactly_one_party",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("mailing", "Mailing"),
                            ("billing", "Billing"),
                            ("shipping", "Shipping"),
                            ("headquarters", "Headquarters"),
                            ("branch", "Branch"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=20,
                        verbose_name="address type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary"),
                ),
                (
                    "line1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Custom label like "Mom\'s House" or "Downtown Office"',
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="django_parties.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="django_parties.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="django_parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "ordering": ["-is_primary", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("person__isnull", False),
                                ("organization__isnull", True),
                                ("group__isnull", True),
                            ),
                            models.Q(
                                ("person__isnull", True),
                                ("organization__isnull", False),
                                ("group__isnull", True),
                            ),
                            models.Q(
                                ("person__isnull", True),
                                ("organization__isnull", True),
                                ("group__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="address_exactly_one_party",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("fax", "Fax"),
                            ("whatsapp", "WhatsApp"),
                            ("main", "Main"),
                            ("toll_free", "Toll Free"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=20,
                        verbose_name="phone type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary"),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="e.g., +1 for US, +52 for Mexico",
                        max_length=5,
                        verbose_name="country code",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="number")),
                (
                    "extension",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="extension"
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=100, verbose_name="label"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "can_receive_sms",
                    models.BooleanField(default=True, verbose_name="can receive SMS"),
                ),
                (
                    "can_receive_whatsapp",
                    models.BooleanField(
                        default=False, verbose_name="can receive WhatsApp"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="django_parties.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="django_parties.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="django_parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "phone number",
                "verbose_name_plural": "phone numbers",
                "ordering": ["-is_primary", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("person__isnull", False),
                                ("organization__isnull", True),
                                ("group__isnull", True),
                            ),
                            models.Q(
                                ("person__isnull", True),
                                ("organization__isnull", False),
                                ("group__isnull", True),
                            ),
                            models.Q(
                                ("person__isnull", True),
                                ("organization__isnull", True),
                                ("group__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="phone_exactly_one_party",
                    )
                ],
            },
        ),
    ]
