# Generated by Django 6.0 on 2026-01-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="person",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="postal code"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="state/province"
            ),
        ),
    ]
