# Generated by Django 6.0 on 2026-01-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_parties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("contractor_individual", "Individual Contractor"),
                    ("contact", "Contact"),
                    ("owner", "Owner/Executive"),
                    ("customer", "Customer"),
                    ("contractor_org", "Contractor Organization"),
                    ("vendor", "Vendor/Supplier"),
                    ("partner", "Business Partner"),
                    ("client", "Client"),
                    ("subsidiary", "Subsidiary"),
                    ("parent_company", "Parent Company"),
                    ("member", "Member"),
                    ("head", "Head of Household"),
                    ("spouse", "Spouse/Partner"),
                    ("dependent", "Dependent"),
                    ("emergency_contact", "Emergency Contact"),
                    ("guardian", "Guardian"),
                    ("parent", "Parent"),
                    ("child", "Child"),
                    ("sibling", "Sibling"),
                    ("manager", "Manager"),
                    ("reports_to", "Reports To"),
                    ("friend", "Friend"),
                    ("relative", "Relative/Family"),
                    ("buddy", "Activity Partner/Buddy"),
                    ("travel_companion", "Travel Companion"),
                    ("instructor", "Instructor/Trainer"),
                    ("student", "Student/Trainee"),
                ],
                max_length=30,
                verbose_name="relationship type",
            ),
        ),
    ]
