# Generated by Django 6.0 on 2026-01-11 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_parties", "0002_add_diver_relationship_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="lead_converted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When lead was converted to customer",
                null=True,
                verbose_name="converted at",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="lead_lost_reason",
            field=models.TextField(
                blank=True,
                help_text="Why the lead was lost (if status=lost)",
                verbose_name="lost reason",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="lead_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member responsible for this lead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_leads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="lead owner",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="lead_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("website", "Website"),
                    ("walk_in", "Walk-in"),
                    ("whatsapp", "WhatsApp"),
                    ("referral", "Referral"),
                    ("hotel", "Hotel Partner"),
                    ("facebook", "Facebook/Instagram"),
                    ("google", "Google Ads"),
                    ("tripadvisor", "TripAdvisor"),
                    ("returning", "Returning Customer"),
                    ("other", "Other"),
                ],
                help_text="How the lead found us",
                max_length=20,
                verbose_name="lead source",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="lead_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                help_text="Pipeline status for leads. NULL means not a lead.",
                max_length=20,
                null=True,
                verbose_name="lead status",
            ),
        ),
        migrations.CreateModel(
            name="LeadStatusEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        help_text="Previous status (blank if new lead)",
                        max_length=20,
                        verbose_name="from status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        max_length=20,
                        verbose_name="to status",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note about this status change",
                        verbose_name="note",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="changed by",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_status_events",
                        to="django_parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead status event",
                "verbose_name_plural": "lead status events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "created_at"],
                        name="django_part_person__3781cc_idx",
                    )
                ],
            },
        ),
    ]
