# Generated by Django 6.0 on 2026-01-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_parties", "0002_remove_person_duplicate_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="address",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("person__isnull", False),
                        ("organization__isnull", True),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("organization__isnull", False),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("organization__isnull", True),
                        ("group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="address_exactly_one_party",
            ),
        ),
        migrations.AddConstraint(
            model_name="email",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("person__isnull", False),
                        ("organization__isnull", True),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("organization__isnull", False),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("organization__isnull", True),
                        ("group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="email_exactly_one_party",
            ),
        ),
        migrations.AddConstraint(
            model_name="partyurl",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("person__isnull", False),
                        ("organization__isnull", True),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("organization__isnull", False),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("organization__isnull", True),
                        ("group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="partyurl_exactly_one_party",
            ),
        ),
        migrations.AddConstraint(
            model_name="phone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("person__isnull", False),
                        ("organization__isnull", True),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("organization__isnull", False),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("person__isnull", True),
                        ("organization__isnull", True),
                        ("group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="phone_exactly_one_party",
            ),
        ),
    ]
