# Generated by Django 6.0 on 2026-01-11 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_parties", "0003_add_lead_fields_and_status_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "body",
                    models.TextField(help_text="Note content", verbose_name="note"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_notes_authored",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_notes",
                        to="django_parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead note",
                "verbose_name_plural": "lead notes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "created_at"],
                        name="django_part_person__f3cd5e_idx",
                    )
                ],
            },
        ),
    ]
