# Generated by Django 6.0 on 2026-01-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_parties", "0003_address_address_exactly_one_party_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="partyrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("from_person__isnull", False),
                        ("from_organization__isnull", True),
                    ),
                    models.Q(
                        ("from_person__isnull", True),
                        ("from_organization__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="partyrelationship_exactly_one_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="partyrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("to_person__isnull", False),
                        ("to_organization__isnull", True),
                        ("to_group__isnull", True),
                    ),
                    models.Q(
                        ("to_person__isnull", True),
                        ("to_organization__isnull", False),
                        ("to_group__isnull", True),
                    ),
                    models.Q(
                        ("to_person__isnull", True),
                        ("to_organization__isnull", True),
                        ("to_group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="partyrelationship_exactly_one_to",
            ),
        ),
    ]
