# Generated by Django 6.0 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_parties", "0004_add_lead_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="visitor_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="UUID from browser cookie for anonymous visitor tracking",
                max_length=36,
                verbose_name="visitor ID",
            ),
        ),
        # Update lead_source choices to include website_chat
        migrations.AlterField(
            model_name="person",
            name="lead_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("website", "Website"),
                    ("website_chat", "Website Chat"),
                    ("walk_in", "Walk-in"),
                    ("whatsapp", "WhatsApp"),
                    ("referral", "Referral"),
                    ("hotel", "Hotel Partner"),
                    ("facebook", "Facebook/Instagram"),
                    ("google", "Google Ads"),
                    ("tripadvisor", "TripAdvisor"),
                    ("returning", "Returning Customer"),
                    ("other", "Other"),
                ],
                help_text="How the lead found us",
                max_length=20,
                verbose_name="lead source",
            ),
        ),
    ]
