# Generated by Django 6.0 on 2026-01-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("django_rbac", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hierarchy_level__gte", 10), ("hierarchy_level__lte", 100)
                ),
                name="role_hierarchy_level_range",
            ),
        ),
    ]
