# Generated by Django 6.0 on 2026-01-03 00:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Transaction description"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the transaction was posted (null = draft)",
                        null=True,
                    ),
                ),
                (
                    "effective_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the transaction is effective (business time)",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the transaction was recorded (system time)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_at", "-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_id",
                    models.CharField(
                        help_text="ID of the account owner (CharField for UUID support)",
                        max_length=255,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        help_text="Account type (receivable, payable, revenue, expense, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="ISO currency code (USD, EUR, etc.)", max_length=3
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional account name",
                        max_length=255,
                    ),
                ),
                (
                    "owner_content_type",
                    models.ForeignKey(
                        help_text="Content type of the account owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Entry amount (internal precision)",
                        max_digits=19,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        help_text="Debit or credit",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Line item description",
                        max_length=500,
                    ),
                ),
                (
                    "effective_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the entry is effective (business time)",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the entry was recorded (system time)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="The account affected by this entry",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="django_ledger.account",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        help_text="The entry this reverses (if this is a reversal)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_entries",
                        to="django_ledger.entry",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="The transaction this entry belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="django_ledger.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_at", "-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["owner_content_type", "owner_id"],
                name="django_ledg_owner_c_b43065_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type"], name="django_ledg_account_ceb1ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["currency"], name="django_ledg_currenc_dbe16b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="entry_amount_positive"
            ),
        ),
    ]
