# Generated by Django 6.0 on 2026-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Account number for accounting standards (e.g., 1000, 2000)",
                max_length=20,
            ),
        ),
    ]
