# Generated by Django 6.0 on 2026-01-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ledger", "0002_add_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this account is active. Inactive accounts cannot receive new entries.",
            ),
        ),
    ]
